# This file is generated by make.paws. Please do not edit here.
#' @importFrom paws.common populate
#' @include backupgateway_service.R
NULL

.backupgateway$associate_gateway_to_server_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(GatewayArn = structure(logical(0), tags = list(type = "string")), ServerArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$associate_gateway_to_server_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(GatewayArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$create_gateway_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(ActivationKey = structure(logical(0), tags = list(type = "string")), GatewayDisplayName = structure(logical(0), tags = list(type = "string")), GatewayType = structure(logical(0), tags = list(type = "string")), Tags = structure(list(structure(list(Key = structure(logical(0), tags = list(type = "string")), Value = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))), tags = list(type = "list"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$create_gateway_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(GatewayArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$delete_gateway_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(GatewayArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$delete_gateway_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(GatewayArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$delete_hypervisor_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(HypervisorArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$delete_hypervisor_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(HypervisorArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$disassociate_gateway_from_server_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(GatewayArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$disassociate_gateway_from_server_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(GatewayArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$get_gateway_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(GatewayArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$get_gateway_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(Gateway = structure(list(GatewayArn = structure(logical(0), tags = list(type = "string")), GatewayDisplayName = structure(logical(0), tags = list(type = "string")), GatewayType = structure(logical(0), tags = list(type = "string")), HypervisorId = structure(logical(0), tags = list(type = "string")), LastSeenTime = structure(logical(0), tags = list(type = "timestamp")), NextUpdateAvailabilityTime = structure(logical(0), tags = list(type = "timestamp")), VpcEndpoint = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$import_hypervisor_configuration_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(Host = structure(logical(0), tags = list(type = "string")), KmsKeyArn = structure(logical(0), tags = list(type = "string")), Name = structure(logical(0), tags = list(type = "string")), Password = structure(logical(0), tags = list(type = "string", sensitive = TRUE)), Tags = structure(list(structure(list(Key = structure(logical(0), tags = list(type = "string")), Value = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))), tags = list(type = "list")), Username = structure(logical(0), tags = list(type = "string", sensitive = TRUE))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$import_hypervisor_configuration_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(HypervisorArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$list_gateways_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(MaxResults = structure(logical(0), tags = list(type = "integer", box = TRUE)), NextToken = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$list_gateways_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(Gateways = structure(list(structure(list(GatewayArn = structure(logical(0), tags = list(type = "string")), GatewayDisplayName = structure(logical(0), tags = list(type = "string")), GatewayType = structure(logical(0), tags = list(type = "string")), HypervisorId = structure(logical(0), tags = list(type = "string")), LastSeenTime = structure(logical(0), tags = list(type = "timestamp"))), tags = list(type = "structure"))), tags = list(type = "list")), NextToken = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$list_hypervisors_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(MaxResults = structure(logical(0), tags = list(type = "integer", box = TRUE)), NextToken = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$list_hypervisors_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(Hypervisors = structure(list(structure(list(Host = structure(logical(0), tags = list(type = "string")), HypervisorArn = structure(logical(0), tags = list(type = "string")), KmsKeyArn = structure(logical(0), tags = list(type = "string")), Name = structure(logical(0), tags = list(type = "string")), State = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))), tags = list(type = "list")), NextToken = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$list_tags_for_resource_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(ResourceArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$list_tags_for_resource_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(ResourceArn = structure(logical(0), tags = list(type = "string")), Tags = structure(list(structure(list(Key = structure(logical(0), tags = list(type = "string")), Value = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))), tags = list(type = "list"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$list_virtual_machines_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(MaxResults = structure(logical(0), tags = list(type = "integer", box = TRUE)), NextToken = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$list_virtual_machines_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(NextToken = structure(logical(0), tags = list(type = "string")), VirtualMachines = structure(list(structure(list(HostName = structure(logical(0), tags = list(type = "string")), HypervisorId = structure(logical(0), tags = list(type = "string")), LastBackupDate = structure(logical(0), tags = list(type = "timestamp")), Name = structure(logical(0), tags = list(type = "string")), Path = structure(logical(0), tags = list(type = "string")), ResourceArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))), tags = list(type = "list"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$put_maintenance_start_time_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(DayOfMonth = structure(logical(0), tags = list(type = "integer", box = TRUE)), DayOfWeek = structure(logical(0), tags = list(type = "integer", box = TRUE)), GatewayArn = structure(logical(0), tags = list(type = "string")), HourOfDay = structure(logical(0), tags = list(type = "integer", box = TRUE)), MinuteOfHour = structure(logical(0), tags = list(type = "integer", box = TRUE))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$put_maintenance_start_time_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(GatewayArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$tag_resource_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(ResourceARN = structure(logical(0), tags = list(type = "string")), Tags = structure(list(structure(list(Key = structure(logical(0), tags = list(type = "string")), Value = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))), tags = list(type = "list"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$tag_resource_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(ResourceARN = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$test_hypervisor_configuration_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(GatewayArn = structure(logical(0), tags = list(type = "string")), Host = structure(logical(0), tags = list(type = "string")), Password = structure(logical(0), tags = list(type = "string", sensitive = TRUE)), Username = structure(logical(0), tags = list(type = "string", sensitive = TRUE))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$test_hypervisor_configuration_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$untag_resource_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(ResourceARN = structure(logical(0), tags = list(type = "string")), TagKeys = structure(list(structure(logical(0), tags = list(type = "string"))), tags = list(type = "list"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$untag_resource_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(ResourceARN = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$update_gateway_information_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(GatewayArn = structure(logical(0), tags = list(type = "string")), GatewayDisplayName = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$update_gateway_information_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(GatewayArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$update_gateway_software_now_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(GatewayArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$update_gateway_software_now_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(GatewayArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$update_hypervisor_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(Host = structure(logical(0), tags = list(type = "string")), HypervisorArn = structure(logical(0), tags = list(type = "string")), Name = structure(logical(0), tags = list(type = "string")), Password = structure(logical(0), tags = list(type = "string", sensitive = TRUE)), Username = structure(logical(0), tags = list(type = "string", sensitive = TRUE))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.backupgateway$update_hypervisor_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(HypervisorArn = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}
