# This file is generated by make.paws. Please do not edit here.
#' @importFrom paws.common populate
#' @include vpclattice_service.R
NULL

.vpclattice$batch_update_rule_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["batch_update_rule_input"]]))
}

.vpclattice$batch_update_rule_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["batch_update_rule_output"]]))
}

.vpclattice$create_access_log_subscription_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_access_log_subscription_input"]]))
}

.vpclattice$create_access_log_subscription_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_access_log_subscription_output"]]))
}

.vpclattice$create_listener_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_listener_input"]]))
}

.vpclattice$create_listener_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_listener_output"]]))
}

.vpclattice$create_resource_configuration_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_resource_configuration_input"]]))
}

.vpclattice$create_resource_configuration_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_resource_configuration_output"]]))
}

.vpclattice$create_resource_gateway_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_resource_gateway_input"]]))
}

.vpclattice$create_resource_gateway_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_resource_gateway_output"]]))
}

.vpclattice$create_rule_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_rule_input"]]))
}

.vpclattice$create_rule_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_rule_output"]]))
}

.vpclattice$create_service_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_service_input"]]))
}

.vpclattice$create_service_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_service_output"]]))
}

.vpclattice$create_service_network_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_service_network_input"]]))
}

.vpclattice$create_service_network_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_service_network_output"]]))
}

.vpclattice$create_service_network_resource_association_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_service_network_resource_association_input"]]))
}

.vpclattice$create_service_network_resource_association_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_service_network_resource_association_output"]]))
}

.vpclattice$create_service_network_service_association_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_service_network_service_association_input"]]))
}

.vpclattice$create_service_network_service_association_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_service_network_service_association_output"]]))
}

.vpclattice$create_service_network_vpc_association_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_service_network_vpc_association_input"]]))
}

.vpclattice$create_service_network_vpc_association_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_service_network_vpc_association_output"]]))
}

.vpclattice$create_target_group_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_target_group_input"]]))
}

.vpclattice$create_target_group_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["create_target_group_output"]]))
}

.vpclattice$delete_access_log_subscription_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_access_log_subscription_input"]]))
}

.vpclattice$delete_access_log_subscription_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_access_log_subscription_output"]]))
}

.vpclattice$delete_auth_policy_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_auth_policy_input"]]))
}

.vpclattice$delete_auth_policy_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_auth_policy_output"]]))
}

.vpclattice$delete_domain_verification_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_domain_verification_input"]]))
}

.vpclattice$delete_domain_verification_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_domain_verification_output"]]))
}

.vpclattice$delete_listener_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_listener_input"]]))
}

.vpclattice$delete_listener_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_listener_output"]]))
}

.vpclattice$delete_resource_configuration_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_resource_configuration_input"]]))
}

.vpclattice$delete_resource_configuration_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_resource_configuration_output"]]))
}

.vpclattice$delete_resource_endpoint_association_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_resource_endpoint_association_input"]]))
}

.vpclattice$delete_resource_endpoint_association_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_resource_endpoint_association_output"]]))
}

.vpclattice$delete_resource_gateway_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_resource_gateway_input"]]))
}

.vpclattice$delete_resource_gateway_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_resource_gateway_output"]]))
}

.vpclattice$delete_resource_policy_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_resource_policy_input"]]))
}

.vpclattice$delete_resource_policy_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_resource_policy_output"]]))
}

.vpclattice$delete_rule_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_rule_input"]]))
}

.vpclattice$delete_rule_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_rule_output"]]))
}

.vpclattice$delete_service_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_service_input"]]))
}

.vpclattice$delete_service_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_service_output"]]))
}

.vpclattice$delete_service_network_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_service_network_input"]]))
}

.vpclattice$delete_service_network_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_service_network_output"]]))
}

.vpclattice$delete_service_network_resource_association_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_service_network_resource_association_input"]]))
}

.vpclattice$delete_service_network_resource_association_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_service_network_resource_association_output"]]))
}

.vpclattice$delete_service_network_service_association_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_service_network_service_association_input"]]))
}

.vpclattice$delete_service_network_service_association_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_service_network_service_association_output"]]))
}

.vpclattice$delete_service_network_vpc_association_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_service_network_vpc_association_input"]]))
}

.vpclattice$delete_service_network_vpc_association_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_service_network_vpc_association_output"]]))
}

.vpclattice$delete_target_group_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_target_group_input"]]))
}

.vpclattice$delete_target_group_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["delete_target_group_output"]]))
}

.vpclattice$deregister_targets_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["deregister_targets_input"]]))
}

.vpclattice$deregister_targets_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["deregister_targets_output"]]))
}

.vpclattice$get_access_log_subscription_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_access_log_subscription_input"]]))
}

.vpclattice$get_access_log_subscription_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_access_log_subscription_output"]]))
}

.vpclattice$get_auth_policy_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_auth_policy_input"]]))
}

.vpclattice$get_auth_policy_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_auth_policy_output"]]))
}

.vpclattice$get_domain_verification_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_domain_verification_input"]]))
}

.vpclattice$get_domain_verification_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_domain_verification_output"]]))
}

.vpclattice$get_listener_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_listener_input"]]))
}

.vpclattice$get_listener_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_listener_output"]]))
}

.vpclattice$get_resource_configuration_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_resource_configuration_input"]]))
}

.vpclattice$get_resource_configuration_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_resource_configuration_output"]]))
}

.vpclattice$get_resource_gateway_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_resource_gateway_input"]]))
}

.vpclattice$get_resource_gateway_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_resource_gateway_output"]]))
}

.vpclattice$get_resource_policy_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_resource_policy_input"]]))
}

.vpclattice$get_resource_policy_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_resource_policy_output"]]))
}

.vpclattice$get_rule_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_rule_input"]]))
}

.vpclattice$get_rule_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_rule_output"]]))
}

.vpclattice$get_service_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_service_input"]]))
}

.vpclattice$get_service_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_service_output"]]))
}

.vpclattice$get_service_network_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_service_network_input"]]))
}

.vpclattice$get_service_network_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_service_network_output"]]))
}

.vpclattice$get_service_network_resource_association_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_service_network_resource_association_input"]]))
}

.vpclattice$get_service_network_resource_association_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_service_network_resource_association_output"]]))
}

.vpclattice$get_service_network_service_association_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_service_network_service_association_input"]]))
}

.vpclattice$get_service_network_service_association_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_service_network_service_association_output"]]))
}

.vpclattice$get_service_network_vpc_association_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_service_network_vpc_association_input"]]))
}

.vpclattice$get_service_network_vpc_association_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_service_network_vpc_association_output"]]))
}

.vpclattice$get_target_group_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_target_group_input"]]))
}

.vpclattice$get_target_group_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["get_target_group_output"]]))
}

.vpclattice$list_access_log_subscriptions_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_access_log_subscriptions_input"]]))
}

.vpclattice$list_access_log_subscriptions_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_access_log_subscriptions_output"]]))
}

.vpclattice$list_domain_verifications_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_domain_verifications_input"]]))
}

.vpclattice$list_domain_verifications_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_domain_verifications_output"]]))
}

.vpclattice$list_listeners_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_listeners_input"]]))
}

.vpclattice$list_listeners_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_listeners_output"]]))
}

.vpclattice$list_resource_configurations_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_resource_configurations_input"]]))
}

.vpclattice$list_resource_configurations_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_resource_configurations_output"]]))
}

.vpclattice$list_resource_endpoint_associations_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_resource_endpoint_associations_input"]]))
}

.vpclattice$list_resource_endpoint_associations_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_resource_endpoint_associations_output"]]))
}

.vpclattice$list_resource_gateways_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_resource_gateways_input"]]))
}

.vpclattice$list_resource_gateways_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_resource_gateways_output"]]))
}

.vpclattice$list_rules_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_rules_input"]]))
}

.vpclattice$list_rules_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_rules_output"]]))
}

.vpclattice$list_service_network_resource_associations_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_service_network_resource_associations_input"]]))
}

.vpclattice$list_service_network_resource_associations_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_service_network_resource_associations_output"]]))
}

.vpclattice$list_service_network_service_associations_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_service_network_service_associations_input"]]))
}

.vpclattice$list_service_network_service_associations_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_service_network_service_associations_output"]]))
}

.vpclattice$list_service_network_vpc_associations_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_service_network_vpc_associations_input"]]))
}

.vpclattice$list_service_network_vpc_associations_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_service_network_vpc_associations_output"]]))
}

.vpclattice$list_service_network_vpc_endpoint_associations_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_service_network_vpc_endpoint_associations_input"]]))
}

.vpclattice$list_service_network_vpc_endpoint_associations_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_service_network_vpc_endpoint_associations_output"]]))
}

.vpclattice$list_service_networks_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_service_networks_input"]]))
}

.vpclattice$list_service_networks_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_service_networks_output"]]))
}

.vpclattice$list_services_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_services_input"]]))
}

.vpclattice$list_services_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_services_output"]]))
}

.vpclattice$list_tags_for_resource_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_tags_for_resource_input"]]))
}

.vpclattice$list_tags_for_resource_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_tags_for_resource_output"]]))
}

.vpclattice$list_target_groups_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_target_groups_input"]]))
}

.vpclattice$list_target_groups_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_target_groups_output"]]))
}

.vpclattice$list_targets_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_targets_input"]]))
}

.vpclattice$list_targets_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["list_targets_output"]]))
}

.vpclattice$put_auth_policy_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["put_auth_policy_input"]]))
}

.vpclattice$put_auth_policy_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["put_auth_policy_output"]]))
}

.vpclattice$put_resource_policy_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["put_resource_policy_input"]]))
}

.vpclattice$put_resource_policy_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["put_resource_policy_output"]]))
}

.vpclattice$register_targets_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["register_targets_input"]]))
}

.vpclattice$register_targets_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["register_targets_output"]]))
}

.vpclattice$start_domain_verification_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["start_domain_verification_input"]]))
}

.vpclattice$start_domain_verification_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["start_domain_verification_output"]]))
}

.vpclattice$tag_resource_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["tag_resource_input"]]))
}

.vpclattice$tag_resource_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["tag_resource_output"]]))
}

.vpclattice$untag_resource_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["untag_resource_input"]]))
}

.vpclattice$untag_resource_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["untag_resource_output"]]))
}

.vpclattice$update_access_log_subscription_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_access_log_subscription_input"]]))
}

.vpclattice$update_access_log_subscription_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_access_log_subscription_output"]]))
}

.vpclattice$update_listener_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_listener_input"]]))
}

.vpclattice$update_listener_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_listener_output"]]))
}

.vpclattice$update_resource_configuration_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_resource_configuration_input"]]))
}

.vpclattice$update_resource_configuration_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_resource_configuration_output"]]))
}

.vpclattice$update_resource_gateway_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_resource_gateway_input"]]))
}

.vpclattice$update_resource_gateway_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_resource_gateway_output"]]))
}

.vpclattice$update_rule_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_rule_input"]]))
}

.vpclattice$update_rule_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_rule_output"]]))
}

.vpclattice$update_service_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_service_input"]]))
}

.vpclattice$update_service_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_service_output"]]))
}

.vpclattice$update_service_network_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_service_network_input"]]))
}

.vpclattice$update_service_network_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_service_network_output"]]))
}

.vpclattice$update_service_network_vpc_association_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_service_network_vpc_association_input"]]))
}

.vpclattice$update_service_network_vpc_association_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_service_network_vpc_association_output"]]))
}

.vpclattice$update_target_group_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_target_group_input"]]))
}

.vpclattice$update_target_group_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  return(populate(args, .vpclattice_shapes[["update_target_group_output"]]))
}
