create_channel_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Description = structure(logical(0), 
        locationName = "description", shape = "__string", type = "string"), 
        Id = structure(logical(0), locationName = "id", shape = "__string", 
            type = "string")), shape = "CreateChannelRequest", 
        type = "structure")
    return(populate(args, shape))
}

create_channel_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Arn = structure(logical(0), locationName = "arn", 
        shape = "__string", type = "string"), Description = structure(logical(0), 
        locationName = "description", shape = "__string", type = "string"), 
        HlsIngest = structure(list(IngestEndpoints = structure(list(structure(list(Id = structure(logical(0), 
            locationName = "id", shape = "__string", type = "string"), 
            Password = structure(logical(0), locationName = "password", 
                shape = "__string", type = "string"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string"), 
            Username = structure(logical(0), locationName = "username", 
                shape = "__string", type = "string")), shape = "IngestEndpoint", 
            type = "structure")), locationName = "ingestEndpoints", 
            shape = "__listOfIngestEndpoint", type = "list")), 
            locationName = "hlsIngest", shape = "HlsIngest", 
            type = "structure"), Id = structure(logical(0), locationName = "id", 
            shape = "__string", type = "string")), shape = "CreateChannelResponse", 
        type = "structure")
    return(populate(args, shape))
}

create_origin_endpoint_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(ChannelId = structure(logical(0), 
        locationName = "channelId", shape = "__string", type = "string"), 
        CmafPackage = structure(list(Encryption = structure(list(KeyRotationIntervalSeconds = structure(logical(0), 
            locationName = "keyRotationIntervalSeconds", shape = "__integer", 
            type = "integer"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "CmafEncryption", type = "structure"), HlsManifests = structure(list(structure(list(AdMarkers = structure(logical(0), 
            locationName = "adMarkers", shape = "AdMarkers", 
            type = "string"), Id = structure(logical(0), locationName = "id", 
            shape = "__string", type = "string"), IncludeIframeOnlyStream = structure(logical(0), 
            locationName = "includeIframeOnlyStream", shape = "__boolean", 
            type = "boolean"), ManifestName = structure(logical(0), 
            locationName = "manifestName", shape = "__string", 
            type = "string"), PlaylistType = structure(logical(0), 
            locationName = "playlistType", shape = "PlaylistType", 
            type = "string"), PlaylistWindowSeconds = structure(logical(0), 
            locationName = "playlistWindowSeconds", shape = "__integer", 
            type = "integer"), ProgramDateTimeIntervalSeconds = structure(logical(0), 
            locationName = "programDateTimeIntervalSeconds", 
            shape = "__integer", type = "integer")), shape = "HlsManifestCreateOrUpdateParameters", 
            type = "structure")), locationName = "hlsManifests", 
            shape = "__listOfHlsManifestCreateOrUpdateParameters", 
            type = "list"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), SegmentPrefix = structure(logical(0), 
            locationName = "segmentPrefix", shape = "__string", 
            type = "string"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure")), 
            locationName = "cmafPackage", shape = "CmafPackageCreateOrUpdateParameters", 
            type = "structure"), DashPackage = structure(list(Encryption = structure(list(KeyRotationIntervalSeconds = structure(logical(0), 
            locationName = "keyRotationIntervalSeconds", shape = "__integer", 
            type = "integer"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "DashEncryption", type = "structure"), ManifestWindowSeconds = structure(logical(0), 
            locationName = "manifestWindowSeconds", shape = "__integer", 
            type = "integer"), MinBufferTimeSeconds = structure(logical(0), 
            locationName = "minBufferTimeSeconds", shape = "__integer", 
            type = "integer"), MinUpdatePeriodSeconds = structure(logical(0), 
            locationName = "minUpdatePeriodSeconds", shape = "__integer", 
            type = "integer"), PeriodTriggers = structure(list(structure(logical(0), 
            shape = "__PeriodTriggersElement", type = "string")), 
            locationName = "periodTriggers", shape = "__listOf__PeriodTriggersElement", 
            type = "list"), Profile = structure(logical(0), locationName = "profile", 
            shape = "Profile", type = "string"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure"), SuggestedPresentationDelaySeconds = structure(logical(0), 
            locationName = "suggestedPresentationDelaySeconds", 
            shape = "__integer", type = "integer")), locationName = "dashPackage", 
            shape = "DashPackage", type = "structure"), Description = structure(logical(0), 
            locationName = "description", shape = "__string", 
            type = "string"), HlsPackage = structure(list(AdMarkers = structure(logical(0), 
            locationName = "adMarkers", shape = "AdMarkers", 
            type = "string"), Encryption = structure(list(ConstantInitializationVector = structure(logical(0), 
            locationName = "constantInitializationVector", shape = "__string", 
            type = "string"), EncryptionMethod = structure(logical(0), 
            locationName = "encryptionMethod", shape = "EncryptionMethod", 
            type = "string"), KeyRotationIntervalSeconds = structure(logical(0), 
            locationName = "keyRotationIntervalSeconds", shape = "__integer", 
            type = "integer"), RepeatExtXKey = structure(logical(0), 
            locationName = "repeatExtXKey", shape = "__boolean", 
            type = "boolean"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "HlsEncryption", type = "structure"), IncludeIframeOnlyStream = structure(logical(0), 
            locationName = "includeIframeOnlyStream", shape = "__boolean", 
            type = "boolean"), PlaylistType = structure(logical(0), 
            locationName = "playlistType", shape = "PlaylistType", 
            type = "string"), PlaylistWindowSeconds = structure(logical(0), 
            locationName = "playlistWindowSeconds", shape = "__integer", 
            type = "integer"), ProgramDateTimeIntervalSeconds = structure(logical(0), 
            locationName = "programDateTimeIntervalSeconds", 
            shape = "__integer", type = "integer"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure"), UseAudioRenditionGroup = structure(logical(0), 
            locationName = "useAudioRenditionGroup", shape = "__boolean", 
            type = "boolean")), locationName = "hlsPackage", 
            shape = "HlsPackage", type = "structure"), Id = structure(logical(0), 
            locationName = "id", shape = "__string", type = "string"), 
        ManifestName = structure(logical(0), locationName = "manifestName", 
            shape = "__string", type = "string"), MssPackage = structure(list(Encryption = structure(list(SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "MssEncryption", type = "structure"), ManifestWindowSeconds = structure(logical(0), 
            locationName = "manifestWindowSeconds", shape = "__integer", 
            type = "integer"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure")), 
            locationName = "mssPackage", shape = "MssPackage", 
            type = "structure"), StartoverWindowSeconds = structure(logical(0), 
            locationName = "startoverWindowSeconds", shape = "__integer", 
            type = "integer"), TimeDelaySeconds = structure(logical(0), 
            locationName = "timeDelaySeconds", shape = "__integer", 
            type = "integer"), Whitelist = structure(list(structure(logical(0), 
            shape = "__string", type = "string")), locationName = "whitelist", 
            shape = "__listOf__string", type = "list")), shape = "CreateOriginEndpointRequest", 
        type = "structure")
    return(populate(args, shape))
}

create_origin_endpoint_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Arn = structure(logical(0), locationName = "arn", 
        shape = "__string", type = "string"), ChannelId = structure(logical(0), 
        locationName = "channelId", shape = "__string", type = "string"), 
        CmafPackage = structure(list(Encryption = structure(list(KeyRotationIntervalSeconds = structure(logical(0), 
            locationName = "keyRotationIntervalSeconds", shape = "__integer", 
            type = "integer"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "CmafEncryption", type = "structure"), HlsManifests = structure(list(structure(list(AdMarkers = structure(logical(0), 
            locationName = "adMarkers", shape = "AdMarkers", 
            type = "string"), Id = structure(logical(0), locationName = "id", 
            shape = "__string", type = "string"), IncludeIframeOnlyStream = structure(logical(0), 
            locationName = "includeIframeOnlyStream", shape = "__boolean", 
            type = "boolean"), ManifestName = structure(logical(0), 
            locationName = "manifestName", shape = "__string", 
            type = "string"), PlaylistType = structure(logical(0), 
            locationName = "playlistType", shape = "PlaylistType", 
            type = "string"), PlaylistWindowSeconds = structure(logical(0), 
            locationName = "playlistWindowSeconds", shape = "__integer", 
            type = "integer"), ProgramDateTimeIntervalSeconds = structure(logical(0), 
            locationName = "programDateTimeIntervalSeconds", 
            shape = "__integer", type = "integer"), Url = structure(logical(0), 
            locationName = "url", shape = "__string", type = "string")), 
            shape = "HlsManifest", type = "structure")), locationName = "hlsManifests", 
            shape = "__listOfHlsManifest", type = "list"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), SegmentPrefix = structure(logical(0), 
            locationName = "segmentPrefix", shape = "__string", 
            type = "string"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure")), 
            locationName = "cmafPackage", shape = "CmafPackage", 
            type = "structure"), DashPackage = structure(list(Encryption = structure(list(KeyRotationIntervalSeconds = structure(logical(0), 
            locationName = "keyRotationIntervalSeconds", shape = "__integer", 
            type = "integer"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "DashEncryption", type = "structure"), ManifestWindowSeconds = structure(logical(0), 
            locationName = "manifestWindowSeconds", shape = "__integer", 
            type = "integer"), MinBufferTimeSeconds = structure(logical(0), 
            locationName = "minBufferTimeSeconds", shape = "__integer", 
            type = "integer"), MinUpdatePeriodSeconds = structure(logical(0), 
            locationName = "minUpdatePeriodSeconds", shape = "__integer", 
            type = "integer"), PeriodTriggers = structure(list(structure(logical(0), 
            shape = "__PeriodTriggersElement", type = "string")), 
            locationName = "periodTriggers", shape = "__listOf__PeriodTriggersElement", 
            type = "list"), Profile = structure(logical(0), locationName = "profile", 
            shape = "Profile", type = "string"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure"), SuggestedPresentationDelaySeconds = structure(logical(0), 
            locationName = "suggestedPresentationDelaySeconds", 
            shape = "__integer", type = "integer")), locationName = "dashPackage", 
            shape = "DashPackage", type = "structure"), Description = structure(logical(0), 
            locationName = "description", shape = "__string", 
            type = "string"), HlsPackage = structure(list(AdMarkers = structure(logical(0), 
            locationName = "adMarkers", shape = "AdMarkers", 
            type = "string"), Encryption = structure(list(ConstantInitializationVector = structure(logical(0), 
            locationName = "constantInitializationVector", shape = "__string", 
            type = "string"), EncryptionMethod = structure(logical(0), 
            locationName = "encryptionMethod", shape = "EncryptionMethod", 
            type = "string"), KeyRotationIntervalSeconds = structure(logical(0), 
            locationName = "keyRotationIntervalSeconds", shape = "__integer", 
            type = "integer"), RepeatExtXKey = structure(logical(0), 
            locationName = "repeatExtXKey", shape = "__boolean", 
            type = "boolean"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "HlsEncryption", type = "structure"), IncludeIframeOnlyStream = structure(logical(0), 
            locationName = "includeIframeOnlyStream", shape = "__boolean", 
            type = "boolean"), PlaylistType = structure(logical(0), 
            locationName = "playlistType", shape = "PlaylistType", 
            type = "string"), PlaylistWindowSeconds = structure(logical(0), 
            locationName = "playlistWindowSeconds", shape = "__integer", 
            type = "integer"), ProgramDateTimeIntervalSeconds = structure(logical(0), 
            locationName = "programDateTimeIntervalSeconds", 
            shape = "__integer", type = "integer"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure"), UseAudioRenditionGroup = structure(logical(0), 
            locationName = "useAudioRenditionGroup", shape = "__boolean", 
            type = "boolean")), locationName = "hlsPackage", 
            shape = "HlsPackage", type = "structure"), Id = structure(logical(0), 
            locationName = "id", shape = "__string", type = "string"), 
        ManifestName = structure(logical(0), locationName = "manifestName", 
            shape = "__string", type = "string"), MssPackage = structure(list(Encryption = structure(list(SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "MssEncryption", type = "structure"), ManifestWindowSeconds = structure(logical(0), 
            locationName = "manifestWindowSeconds", shape = "__integer", 
            type = "integer"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure")), 
            locationName = "mssPackage", shape = "MssPackage", 
            type = "structure"), StartoverWindowSeconds = structure(logical(0), 
            locationName = "startoverWindowSeconds", shape = "__integer", 
            type = "integer"), TimeDelaySeconds = structure(logical(0), 
            locationName = "timeDelaySeconds", shape = "__integer", 
            type = "integer"), Url = structure(logical(0), locationName = "url", 
            shape = "__string", type = "string"), Whitelist = structure(list(structure(logical(0), 
            shape = "__string", type = "string")), locationName = "whitelist", 
            shape = "__listOf__string", type = "list")), shape = "CreateOriginEndpointResponse", 
        type = "structure")
    return(populate(args, shape))
}

delete_channel_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Id = structure(logical(0), location = "uri", 
        locationName = "id", shape = "__string", type = "string")), 
        shape = "DeleteChannelRequest", type = "structure")
    return(populate(args, shape))
}

delete_channel_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(), shape = "DeleteChannelResponse", 
        type = "structure")
    return(populate(args, shape))
}

delete_origin_endpoint_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Id = structure(logical(0), location = "uri", 
        locationName = "id", shape = "__string", type = "string")), 
        shape = "DeleteOriginEndpointRequest", type = "structure")
    return(populate(args, shape))
}

delete_origin_endpoint_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(), shape = "DeleteOriginEndpointResponse", 
        type = "structure")
    return(populate(args, shape))
}

describe_channel_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Id = structure(logical(0), location = "uri", 
        locationName = "id", shape = "__string", type = "string")), 
        shape = "DescribeChannelRequest", type = "structure")
    return(populate(args, shape))
}

describe_channel_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Arn = structure(logical(0), locationName = "arn", 
        shape = "__string", type = "string"), Description = structure(logical(0), 
        locationName = "description", shape = "__string", type = "string"), 
        HlsIngest = structure(list(IngestEndpoints = structure(list(structure(list(Id = structure(logical(0), 
            locationName = "id", shape = "__string", type = "string"), 
            Password = structure(logical(0), locationName = "password", 
                shape = "__string", type = "string"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string"), 
            Username = structure(logical(0), locationName = "username", 
                shape = "__string", type = "string")), shape = "IngestEndpoint", 
            type = "structure")), locationName = "ingestEndpoints", 
            shape = "__listOfIngestEndpoint", type = "list")), 
            locationName = "hlsIngest", shape = "HlsIngest", 
            type = "structure"), Id = structure(logical(0), locationName = "id", 
            shape = "__string", type = "string")), shape = "DescribeChannelResponse", 
        type = "structure")
    return(populate(args, shape))
}

describe_origin_endpoint_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Id = structure(logical(0), location = "uri", 
        locationName = "id", shape = "__string", type = "string")), 
        shape = "DescribeOriginEndpointRequest", type = "structure")
    return(populate(args, shape))
}

describe_origin_endpoint_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Arn = structure(logical(0), locationName = "arn", 
        shape = "__string", type = "string"), ChannelId = structure(logical(0), 
        locationName = "channelId", shape = "__string", type = "string"), 
        CmafPackage = structure(list(Encryption = structure(list(KeyRotationIntervalSeconds = structure(logical(0), 
            locationName = "keyRotationIntervalSeconds", shape = "__integer", 
            type = "integer"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "CmafEncryption", type = "structure"), HlsManifests = structure(list(structure(list(AdMarkers = structure(logical(0), 
            locationName = "adMarkers", shape = "AdMarkers", 
            type = "string"), Id = structure(logical(0), locationName = "id", 
            shape = "__string", type = "string"), IncludeIframeOnlyStream = structure(logical(0), 
            locationName = "includeIframeOnlyStream", shape = "__boolean", 
            type = "boolean"), ManifestName = structure(logical(0), 
            locationName = "manifestName", shape = "__string", 
            type = "string"), PlaylistType = structure(logical(0), 
            locationName = "playlistType", shape = "PlaylistType", 
            type = "string"), PlaylistWindowSeconds = structure(logical(0), 
            locationName = "playlistWindowSeconds", shape = "__integer", 
            type = "integer"), ProgramDateTimeIntervalSeconds = structure(logical(0), 
            locationName = "programDateTimeIntervalSeconds", 
            shape = "__integer", type = "integer"), Url = structure(logical(0), 
            locationName = "url", shape = "__string", type = "string")), 
            shape = "HlsManifest", type = "structure")), locationName = "hlsManifests", 
            shape = "__listOfHlsManifest", type = "list"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), SegmentPrefix = structure(logical(0), 
            locationName = "segmentPrefix", shape = "__string", 
            type = "string"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure")), 
            locationName = "cmafPackage", shape = "CmafPackage", 
            type = "structure"), DashPackage = structure(list(Encryption = structure(list(KeyRotationIntervalSeconds = structure(logical(0), 
            locationName = "keyRotationIntervalSeconds", shape = "__integer", 
            type = "integer"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "DashEncryption", type = "structure"), ManifestWindowSeconds = structure(logical(0), 
            locationName = "manifestWindowSeconds", shape = "__integer", 
            type = "integer"), MinBufferTimeSeconds = structure(logical(0), 
            locationName = "minBufferTimeSeconds", shape = "__integer", 
            type = "integer"), MinUpdatePeriodSeconds = structure(logical(0), 
            locationName = "minUpdatePeriodSeconds", shape = "__integer", 
            type = "integer"), PeriodTriggers = structure(list(structure(logical(0), 
            shape = "__PeriodTriggersElement", type = "string")), 
            locationName = "periodTriggers", shape = "__listOf__PeriodTriggersElement", 
            type = "list"), Profile = structure(logical(0), locationName = "profile", 
            shape = "Profile", type = "string"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure"), SuggestedPresentationDelaySeconds = structure(logical(0), 
            locationName = "suggestedPresentationDelaySeconds", 
            shape = "__integer", type = "integer")), locationName = "dashPackage", 
            shape = "DashPackage", type = "structure"), Description = structure(logical(0), 
            locationName = "description", shape = "__string", 
            type = "string"), HlsPackage = structure(list(AdMarkers = structure(logical(0), 
            locationName = "adMarkers", shape = "AdMarkers", 
            type = "string"), Encryption = structure(list(ConstantInitializationVector = structure(logical(0), 
            locationName = "constantInitializationVector", shape = "__string", 
            type = "string"), EncryptionMethod = structure(logical(0), 
            locationName = "encryptionMethod", shape = "EncryptionMethod", 
            type = "string"), KeyRotationIntervalSeconds = structure(logical(0), 
            locationName = "keyRotationIntervalSeconds", shape = "__integer", 
            type = "integer"), RepeatExtXKey = structure(logical(0), 
            locationName = "repeatExtXKey", shape = "__boolean", 
            type = "boolean"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "HlsEncryption", type = "structure"), IncludeIframeOnlyStream = structure(logical(0), 
            locationName = "includeIframeOnlyStream", shape = "__boolean", 
            type = "boolean"), PlaylistType = structure(logical(0), 
            locationName = "playlistType", shape = "PlaylistType", 
            type = "string"), PlaylistWindowSeconds = structure(logical(0), 
            locationName = "playlistWindowSeconds", shape = "__integer", 
            type = "integer"), ProgramDateTimeIntervalSeconds = structure(logical(0), 
            locationName = "programDateTimeIntervalSeconds", 
            shape = "__integer", type = "integer"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure"), UseAudioRenditionGroup = structure(logical(0), 
            locationName = "useAudioRenditionGroup", shape = "__boolean", 
            type = "boolean")), locationName = "hlsPackage", 
            shape = "HlsPackage", type = "structure"), Id = structure(logical(0), 
            locationName = "id", shape = "__string", type = "string"), 
        ManifestName = structure(logical(0), locationName = "manifestName", 
            shape = "__string", type = "string"), MssPackage = structure(list(Encryption = structure(list(SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "MssEncryption", type = "structure"), ManifestWindowSeconds = structure(logical(0), 
            locationName = "manifestWindowSeconds", shape = "__integer", 
            type = "integer"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure")), 
            locationName = "mssPackage", shape = "MssPackage", 
            type = "structure"), StartoverWindowSeconds = structure(logical(0), 
            locationName = "startoverWindowSeconds", shape = "__integer", 
            type = "integer"), TimeDelaySeconds = structure(logical(0), 
            locationName = "timeDelaySeconds", shape = "__integer", 
            type = "integer"), Url = structure(logical(0), locationName = "url", 
            shape = "__string", type = "string"), Whitelist = structure(list(structure(logical(0), 
            shape = "__string", type = "string")), locationName = "whitelist", 
            shape = "__listOf__string", type = "list")), shape = "DescribeOriginEndpointResponse", 
        type = "structure")
    return(populate(args, shape))
}

list_channels_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(MaxResults = structure(logical(0), 
        location = "querystring", locationName = "maxResults", 
        shape = "MaxResults", max = 1000L, min = 1L, type = "integer"), 
        NextToken = structure(logical(0), location = "querystring", 
            locationName = "nextToken", shape = "__string", type = "string")), 
        shape = "ListChannelsRequest", type = "structure")
    return(populate(args, shape))
}

list_channels_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Channels = structure(list(structure(list(Arn = structure(logical(0), 
        locationName = "arn", shape = "__string", type = "string"), 
        Description = structure(logical(0), locationName = "description", 
            shape = "__string", type = "string"), HlsIngest = structure(list(IngestEndpoints = structure(list(structure(list(Id = structure(logical(0), 
            locationName = "id", shape = "__string", type = "string"), 
            Password = structure(logical(0), locationName = "password", 
                shape = "__string", type = "string"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string"), 
            Username = structure(logical(0), locationName = "username", 
                shape = "__string", type = "string")), shape = "IngestEndpoint", 
            type = "structure")), locationName = "ingestEndpoints", 
            shape = "__listOfIngestEndpoint", type = "list")), 
            locationName = "hlsIngest", shape = "HlsIngest", 
            type = "structure"), Id = structure(logical(0), locationName = "id", 
            shape = "__string", type = "string")), shape = "Channel", 
        type = "structure")), locationName = "channels", shape = "__listOfChannel", 
        type = "list"), NextToken = structure(logical(0), locationName = "nextToken", 
        shape = "__string", type = "string")), shape = "ListChannelsResponse", 
        type = "structure")
    return(populate(args, shape))
}

list_origin_endpoints_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(ChannelId = structure(logical(0), 
        location = "querystring", locationName = "channelId", 
        shape = "__string", type = "string"), MaxResults = structure(logical(0), 
        location = "querystring", locationName = "maxResults", 
        shape = "MaxResults", max = 1000L, min = 1L, type = "integer"), 
        NextToken = structure(logical(0), location = "querystring", 
            locationName = "nextToken", shape = "__string", type = "string")), 
        shape = "ListOriginEndpointsRequest", type = "structure")
    return(populate(args, shape))
}

list_origin_endpoints_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(NextToken = structure(logical(0), 
        locationName = "nextToken", shape = "__string", type = "string"), 
        OriginEndpoints = structure(list(structure(list(Arn = structure(logical(0), 
            locationName = "arn", shape = "__string", type = "string"), 
            ChannelId = structure(logical(0), locationName = "channelId", 
                shape = "__string", type = "string"), CmafPackage = structure(list(Encryption = structure(list(KeyRotationIntervalSeconds = structure(logical(0), 
                locationName = "keyRotationIntervalSeconds", 
                shape = "__integer", type = "integer"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
                locationName = "resourceId", shape = "__string", 
                type = "string"), RoleArn = structure(logical(0), 
                locationName = "roleArn", shape = "__string", 
                type = "string"), SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
                locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
                type = "structure")), locationName = "encryption", 
                shape = "CmafEncryption", type = "structure"), 
                HlsManifests = structure(list(structure(list(AdMarkers = structure(logical(0), 
                  locationName = "adMarkers", shape = "AdMarkers", 
                  type = "string"), Id = structure(logical(0), 
                  locationName = "id", shape = "__string", type = "string"), 
                  IncludeIframeOnlyStream = structure(logical(0), 
                    locationName = "includeIframeOnlyStream", 
                    shape = "__boolean", type = "boolean"), ManifestName = structure(logical(0), 
                    locationName = "manifestName", shape = "__string", 
                    type = "string"), PlaylistType = structure(logical(0), 
                    locationName = "playlistType", shape = "PlaylistType", 
                    type = "string"), PlaylistWindowSeconds = structure(logical(0), 
                    locationName = "playlistWindowSeconds", shape = "__integer", 
                    type = "integer"), ProgramDateTimeIntervalSeconds = structure(logical(0), 
                    locationName = "programDateTimeIntervalSeconds", 
                    shape = "__integer", type = "integer"), Url = structure(logical(0), 
                    locationName = "url", shape = "__string", 
                    type = "string")), shape = "HlsManifest", 
                  type = "structure")), locationName = "hlsManifests", 
                  shape = "__listOfHlsManifest", type = "list"), 
                SegmentDurationSeconds = structure(logical(0), 
                  locationName = "segmentDurationSeconds", shape = "__integer", 
                  type = "integer"), SegmentPrefix = structure(logical(0), 
                  locationName = "segmentPrefix", shape = "__string", 
                  type = "string"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
                  locationName = "maxVideoBitsPerSecond", shape = "__integer", 
                  type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
                  locationName = "minVideoBitsPerSecond", shape = "__integer", 
                  type = "integer"), StreamOrder = structure(logical(0), 
                  locationName = "streamOrder", shape = "StreamOrder", 
                  type = "string")), locationName = "streamSelection", 
                  shape = "StreamSelection", type = "structure")), 
                locationName = "cmafPackage", shape = "CmafPackage", 
                type = "structure"), DashPackage = structure(list(Encryption = structure(list(KeyRotationIntervalSeconds = structure(logical(0), 
                locationName = "keyRotationIntervalSeconds", 
                shape = "__integer", type = "integer"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
                locationName = "resourceId", shape = "__string", 
                type = "string"), RoleArn = structure(logical(0), 
                locationName = "roleArn", shape = "__string", 
                type = "string"), SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
                locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
                type = "structure")), locationName = "encryption", 
                shape = "DashEncryption", type = "structure"), 
                ManifestWindowSeconds = structure(logical(0), 
                  locationName = "manifestWindowSeconds", shape = "__integer", 
                  type = "integer"), MinBufferTimeSeconds = structure(logical(0), 
                  locationName = "minBufferTimeSeconds", shape = "__integer", 
                  type = "integer"), MinUpdatePeriodSeconds = structure(logical(0), 
                  locationName = "minUpdatePeriodSeconds", shape = "__integer", 
                  type = "integer"), PeriodTriggers = structure(list(structure(logical(0), 
                  shape = "__PeriodTriggersElement", type = "string")), 
                  locationName = "periodTriggers", shape = "__listOf__PeriodTriggersElement", 
                  type = "list"), Profile = structure(logical(0), 
                  locationName = "profile", shape = "Profile", 
                  type = "string"), SegmentDurationSeconds = structure(logical(0), 
                  locationName = "segmentDurationSeconds", shape = "__integer", 
                  type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
                  locationName = "maxVideoBitsPerSecond", shape = "__integer", 
                  type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
                  locationName = "minVideoBitsPerSecond", shape = "__integer", 
                  type = "integer"), StreamOrder = structure(logical(0), 
                  locationName = "streamOrder", shape = "StreamOrder", 
                  type = "string")), locationName = "streamSelection", 
                  shape = "StreamSelection", type = "structure"), 
                SuggestedPresentationDelaySeconds = structure(logical(0), 
                  locationName = "suggestedPresentationDelaySeconds", 
                  shape = "__integer", type = "integer")), locationName = "dashPackage", 
                shape = "DashPackage", type = "structure"), Description = structure(logical(0), 
                locationName = "description", shape = "__string", 
                type = "string"), HlsPackage = structure(list(AdMarkers = structure(logical(0), 
                locationName = "adMarkers", shape = "AdMarkers", 
                type = "string"), Encryption = structure(list(ConstantInitializationVector = structure(logical(0), 
                locationName = "constantInitializationVector", 
                shape = "__string", type = "string"), EncryptionMethod = structure(logical(0), 
                locationName = "encryptionMethod", shape = "EncryptionMethod", 
                type = "string"), KeyRotationIntervalSeconds = structure(logical(0), 
                locationName = "keyRotationIntervalSeconds", 
                shape = "__integer", type = "integer"), RepeatExtXKey = structure(logical(0), 
                locationName = "repeatExtXKey", shape = "__boolean", 
                type = "boolean"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
                locationName = "resourceId", shape = "__string", 
                type = "string"), RoleArn = structure(logical(0), 
                locationName = "roleArn", shape = "__string", 
                type = "string"), SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
                locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
                type = "structure")), locationName = "encryption", 
                shape = "HlsEncryption", type = "structure"), 
                IncludeIframeOnlyStream = structure(logical(0), 
                  locationName = "includeIframeOnlyStream", shape = "__boolean", 
                  type = "boolean"), PlaylistType = structure(logical(0), 
                  locationName = "playlistType", shape = "PlaylistType", 
                  type = "string"), PlaylistWindowSeconds = structure(logical(0), 
                  locationName = "playlistWindowSeconds", shape = "__integer", 
                  type = "integer"), ProgramDateTimeIntervalSeconds = structure(logical(0), 
                  locationName = "programDateTimeIntervalSeconds", 
                  shape = "__integer", type = "integer"), SegmentDurationSeconds = structure(logical(0), 
                  locationName = "segmentDurationSeconds", shape = "__integer", 
                  type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
                  locationName = "maxVideoBitsPerSecond", shape = "__integer", 
                  type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
                  locationName = "minVideoBitsPerSecond", shape = "__integer", 
                  type = "integer"), StreamOrder = structure(logical(0), 
                  locationName = "streamOrder", shape = "StreamOrder", 
                  type = "string")), locationName = "streamSelection", 
                  shape = "StreamSelection", type = "structure"), 
                UseAudioRenditionGroup = structure(logical(0), 
                  locationName = "useAudioRenditionGroup", shape = "__boolean", 
                  type = "boolean")), locationName = "hlsPackage", 
                shape = "HlsPackage", type = "structure"), Id = structure(logical(0), 
                locationName = "id", shape = "__string", type = "string"), 
            ManifestName = structure(logical(0), locationName = "manifestName", 
                shape = "__string", type = "string"), MssPackage = structure(list(Encryption = structure(list(SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
                locationName = "resourceId", shape = "__string", 
                type = "string"), RoleArn = structure(logical(0), 
                locationName = "roleArn", shape = "__string", 
                type = "string"), SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
                locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
                type = "structure")), locationName = "encryption", 
                shape = "MssEncryption", type = "structure"), 
                ManifestWindowSeconds = structure(logical(0), 
                  locationName = "manifestWindowSeconds", shape = "__integer", 
                  type = "integer"), SegmentDurationSeconds = structure(logical(0), 
                  locationName = "segmentDurationSeconds", shape = "__integer", 
                  type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
                  locationName = "maxVideoBitsPerSecond", shape = "__integer", 
                  type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
                  locationName = "minVideoBitsPerSecond", shape = "__integer", 
                  type = "integer"), StreamOrder = structure(logical(0), 
                  locationName = "streamOrder", shape = "StreamOrder", 
                  type = "string")), locationName = "streamSelection", 
                  shape = "StreamSelection", type = "structure")), 
                locationName = "mssPackage", shape = "MssPackage", 
                type = "structure"), StartoverWindowSeconds = structure(logical(0), 
                locationName = "startoverWindowSeconds", shape = "__integer", 
                type = "integer"), TimeDelaySeconds = structure(logical(0), 
                locationName = "timeDelaySeconds", shape = "__integer", 
                type = "integer"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string"), 
            Whitelist = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "whitelist", 
                shape = "__listOf__string", type = "list")), 
            shape = "OriginEndpoint", type = "structure")), locationName = "originEndpoints", 
            shape = "__listOfOriginEndpoint", type = "list")), 
        shape = "ListOriginEndpointsResponse", type = "structure")
    return(populate(args, shape))
}

rotate_channel_credentials_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Id = structure(logical(0), location = "uri", 
        locationName = "id", shape = "__string", type = "string")), 
        shape = "RotateChannelCredentialsRequest", deprecated = TRUE, 
        type = "structure")
    return(populate(args, shape))
}

rotate_channel_credentials_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Arn = structure(logical(0), locationName = "arn", 
        shape = "__string", type = "string"), Description = structure(logical(0), 
        locationName = "description", shape = "__string", type = "string"), 
        HlsIngest = structure(list(IngestEndpoints = structure(list(structure(list(Id = structure(logical(0), 
            locationName = "id", shape = "__string", type = "string"), 
            Password = structure(logical(0), locationName = "password", 
                shape = "__string", type = "string"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string"), 
            Username = structure(logical(0), locationName = "username", 
                shape = "__string", type = "string")), shape = "IngestEndpoint", 
            type = "structure")), locationName = "ingestEndpoints", 
            shape = "__listOfIngestEndpoint", type = "list")), 
            locationName = "hlsIngest", shape = "HlsIngest", 
            type = "structure"), Id = structure(logical(0), locationName = "id", 
            shape = "__string", type = "string")), shape = "RotateChannelCredentialsResponse", 
        deprecated = TRUE, type = "structure")
    return(populate(args, shape))
}

rotate_ingest_endpoint_credentials_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Id = structure(logical(0), location = "uri", 
        locationName = "id", shape = "__string", type = "string"), 
        IngestEndpointId = structure(logical(0), location = "uri", 
            locationName = "ingest_endpoint_id", shape = "__string", 
            type = "string")), shape = "RotateIngestEndpointCredentialsRequest", 
        type = "structure")
    return(populate(args, shape))
}

rotate_ingest_endpoint_credentials_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Arn = structure(logical(0), locationName = "arn", 
        shape = "__string", type = "string"), Description = structure(logical(0), 
        locationName = "description", shape = "__string", type = "string"), 
        HlsIngest = structure(list(IngestEndpoints = structure(list(structure(list(Id = structure(logical(0), 
            locationName = "id", shape = "__string", type = "string"), 
            Password = structure(logical(0), locationName = "password", 
                shape = "__string", type = "string"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string"), 
            Username = structure(logical(0), locationName = "username", 
                shape = "__string", type = "string")), shape = "IngestEndpoint", 
            type = "structure")), locationName = "ingestEndpoints", 
            shape = "__listOfIngestEndpoint", type = "list")), 
            locationName = "hlsIngest", shape = "HlsIngest", 
            type = "structure"), Id = structure(logical(0), locationName = "id", 
            shape = "__string", type = "string")), shape = "RotateIngestEndpointCredentialsResponse", 
        type = "structure")
    return(populate(args, shape))
}

update_channel_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Description = structure(logical(0), 
        locationName = "description", shape = "__string", type = "string"), 
        Id = structure(logical(0), location = "uri", locationName = "id", 
            shape = "__string", type = "string")), shape = "UpdateChannelRequest", 
        type = "structure")
    return(populate(args, shape))
}

update_channel_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Arn = structure(logical(0), locationName = "arn", 
        shape = "__string", type = "string"), Description = structure(logical(0), 
        locationName = "description", shape = "__string", type = "string"), 
        HlsIngest = structure(list(IngestEndpoints = structure(list(structure(list(Id = structure(logical(0), 
            locationName = "id", shape = "__string", type = "string"), 
            Password = structure(logical(0), locationName = "password", 
                shape = "__string", type = "string"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string"), 
            Username = structure(logical(0), locationName = "username", 
                shape = "__string", type = "string")), shape = "IngestEndpoint", 
            type = "structure")), locationName = "ingestEndpoints", 
            shape = "__listOfIngestEndpoint", type = "list")), 
            locationName = "hlsIngest", shape = "HlsIngest", 
            type = "structure"), Id = structure(logical(0), locationName = "id", 
            shape = "__string", type = "string")), shape = "UpdateChannelResponse", 
        type = "structure")
    return(populate(args, shape))
}

update_origin_endpoint_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(CmafPackage = structure(list(Encryption = structure(list(KeyRotationIntervalSeconds = structure(logical(0), 
        locationName = "keyRotationIntervalSeconds", shape = "__integer", 
        type = "integer"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
        locationName = "resourceId", shape = "__string", type = "string"), 
        RoleArn = structure(logical(0), locationName = "roleArn", 
            shape = "__string", type = "string"), SystemIds = structure(list(structure(logical(0), 
            shape = "__string", type = "string")), locationName = "systemIds", 
            shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
            locationName = "url", shape = "__string", type = "string")), 
        locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
        type = "structure")), locationName = "encryption", shape = "CmafEncryption", 
        type = "structure"), HlsManifests = structure(list(structure(list(AdMarkers = structure(logical(0), 
        locationName = "adMarkers", shape = "AdMarkers", type = "string"), 
        Id = structure(logical(0), locationName = "id", shape = "__string", 
            type = "string"), IncludeIframeOnlyStream = structure(logical(0), 
            locationName = "includeIframeOnlyStream", shape = "__boolean", 
            type = "boolean"), ManifestName = structure(logical(0), 
            locationName = "manifestName", shape = "__string", 
            type = "string"), PlaylistType = structure(logical(0), 
            locationName = "playlistType", shape = "PlaylistType", 
            type = "string"), PlaylistWindowSeconds = structure(logical(0), 
            locationName = "playlistWindowSeconds", shape = "__integer", 
            type = "integer"), ProgramDateTimeIntervalSeconds = structure(logical(0), 
            locationName = "programDateTimeIntervalSeconds", 
            shape = "__integer", type = "integer")), shape = "HlsManifestCreateOrUpdateParameters", 
        type = "structure")), locationName = "hlsManifests", 
        shape = "__listOfHlsManifestCreateOrUpdateParameters", 
        type = "list"), SegmentDurationSeconds = structure(logical(0), 
        locationName = "segmentDurationSeconds", shape = "__integer", 
        type = "integer"), SegmentPrefix = structure(logical(0), 
        locationName = "segmentPrefix", shape = "__string", type = "string"), 
        StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure")), 
        locationName = "cmafPackage", shape = "CmafPackageCreateOrUpdateParameters", 
        type = "structure"), DashPackage = structure(list(Encryption = structure(list(KeyRotationIntervalSeconds = structure(logical(0), 
        locationName = "keyRotationIntervalSeconds", shape = "__integer", 
        type = "integer"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
        locationName = "resourceId", shape = "__string", type = "string"), 
        RoleArn = structure(logical(0), locationName = "roleArn", 
            shape = "__string", type = "string"), SystemIds = structure(list(structure(logical(0), 
            shape = "__string", type = "string")), locationName = "systemIds", 
            shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
            locationName = "url", shape = "__string", type = "string")), 
        locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
        type = "structure")), locationName = "encryption", shape = "DashEncryption", 
        type = "structure"), ManifestWindowSeconds = structure(logical(0), 
        locationName = "manifestWindowSeconds", shape = "__integer", 
        type = "integer"), MinBufferTimeSeconds = structure(logical(0), 
        locationName = "minBufferTimeSeconds", shape = "__integer", 
        type = "integer"), MinUpdatePeriodSeconds = structure(logical(0), 
        locationName = "minUpdatePeriodSeconds", shape = "__integer", 
        type = "integer"), PeriodTriggers = structure(list(structure(logical(0), 
        shape = "__PeriodTriggersElement", type = "string")), 
        locationName = "periodTriggers", shape = "__listOf__PeriodTriggersElement", 
        type = "list"), Profile = structure(logical(0), locationName = "profile", 
        shape = "Profile", type = "string"), SegmentDurationSeconds = structure(logical(0), 
        locationName = "segmentDurationSeconds", shape = "__integer", 
        type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
        locationName = "maxVideoBitsPerSecond", shape = "__integer", 
        type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
        locationName = "minVideoBitsPerSecond", shape = "__integer", 
        type = "integer"), StreamOrder = structure(logical(0), 
        locationName = "streamOrder", shape = "StreamOrder", 
        type = "string")), locationName = "streamSelection", 
        shape = "StreamSelection", type = "structure"), SuggestedPresentationDelaySeconds = structure(logical(0), 
        locationName = "suggestedPresentationDelaySeconds", shape = "__integer", 
        type = "integer")), locationName = "dashPackage", shape = "DashPackage", 
        type = "structure"), Description = structure(logical(0), 
        locationName = "description", shape = "__string", type = "string"), 
        HlsPackage = structure(list(AdMarkers = structure(logical(0), 
            locationName = "adMarkers", shape = "AdMarkers", 
            type = "string"), Encryption = structure(list(ConstantInitializationVector = structure(logical(0), 
            locationName = "constantInitializationVector", shape = "__string", 
            type = "string"), EncryptionMethod = structure(logical(0), 
            locationName = "encryptionMethod", shape = "EncryptionMethod", 
            type = "string"), KeyRotationIntervalSeconds = structure(logical(0), 
            locationName = "keyRotationIntervalSeconds", shape = "__integer", 
            type = "integer"), RepeatExtXKey = structure(logical(0), 
            locationName = "repeatExtXKey", shape = "__boolean", 
            type = "boolean"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "HlsEncryption", type = "structure"), IncludeIframeOnlyStream = structure(logical(0), 
            locationName = "includeIframeOnlyStream", shape = "__boolean", 
            type = "boolean"), PlaylistType = structure(logical(0), 
            locationName = "playlistType", shape = "PlaylistType", 
            type = "string"), PlaylistWindowSeconds = structure(logical(0), 
            locationName = "playlistWindowSeconds", shape = "__integer", 
            type = "integer"), ProgramDateTimeIntervalSeconds = structure(logical(0), 
            locationName = "programDateTimeIntervalSeconds", 
            shape = "__integer", type = "integer"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure"), UseAudioRenditionGroup = structure(logical(0), 
            locationName = "useAudioRenditionGroup", shape = "__boolean", 
            type = "boolean")), locationName = "hlsPackage", 
            shape = "HlsPackage", type = "structure"), Id = structure(logical(0), 
            location = "uri", locationName = "id", shape = "__string", 
            type = "string"), ManifestName = structure(logical(0), 
            locationName = "manifestName", shape = "__string", 
            type = "string"), MssPackage = structure(list(Encryption = structure(list(SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "MssEncryption", type = "structure"), ManifestWindowSeconds = structure(logical(0), 
            locationName = "manifestWindowSeconds", shape = "__integer", 
            type = "integer"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure")), 
            locationName = "mssPackage", shape = "MssPackage", 
            type = "structure"), StartoverWindowSeconds = structure(logical(0), 
            locationName = "startoverWindowSeconds", shape = "__integer", 
            type = "integer"), TimeDelaySeconds = structure(logical(0), 
            locationName = "timeDelaySeconds", shape = "__integer", 
            type = "integer"), Whitelist = structure(list(structure(logical(0), 
            shape = "__string", type = "string")), locationName = "whitelist", 
            shape = "__listOf__string", type = "list")), shape = "UpdateOriginEndpointRequest", 
        type = "structure")
    return(populate(args, shape))
}

update_origin_endpoint_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Arn = structure(logical(0), locationName = "arn", 
        shape = "__string", type = "string"), ChannelId = structure(logical(0), 
        locationName = "channelId", shape = "__string", type = "string"), 
        CmafPackage = structure(list(Encryption = structure(list(KeyRotationIntervalSeconds = structure(logical(0), 
            locationName = "keyRotationIntervalSeconds", shape = "__integer", 
            type = "integer"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "CmafEncryption", type = "structure"), HlsManifests = structure(list(structure(list(AdMarkers = structure(logical(0), 
            locationName = "adMarkers", shape = "AdMarkers", 
            type = "string"), Id = structure(logical(0), locationName = "id", 
            shape = "__string", type = "string"), IncludeIframeOnlyStream = structure(logical(0), 
            locationName = "includeIframeOnlyStream", shape = "__boolean", 
            type = "boolean"), ManifestName = structure(logical(0), 
            locationName = "manifestName", shape = "__string", 
            type = "string"), PlaylistType = structure(logical(0), 
            locationName = "playlistType", shape = "PlaylistType", 
            type = "string"), PlaylistWindowSeconds = structure(logical(0), 
            locationName = "playlistWindowSeconds", shape = "__integer", 
            type = "integer"), ProgramDateTimeIntervalSeconds = structure(logical(0), 
            locationName = "programDateTimeIntervalSeconds", 
            shape = "__integer", type = "integer"), Url = structure(logical(0), 
            locationName = "url", shape = "__string", type = "string")), 
            shape = "HlsManifest", type = "structure")), locationName = "hlsManifests", 
            shape = "__listOfHlsManifest", type = "list"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), SegmentPrefix = structure(logical(0), 
            locationName = "segmentPrefix", shape = "__string", 
            type = "string"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure")), 
            locationName = "cmafPackage", shape = "CmafPackage", 
            type = "structure"), DashPackage = structure(list(Encryption = structure(list(KeyRotationIntervalSeconds = structure(logical(0), 
            locationName = "keyRotationIntervalSeconds", shape = "__integer", 
            type = "integer"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "DashEncryption", type = "structure"), ManifestWindowSeconds = structure(logical(0), 
            locationName = "manifestWindowSeconds", shape = "__integer", 
            type = "integer"), MinBufferTimeSeconds = structure(logical(0), 
            locationName = "minBufferTimeSeconds", shape = "__integer", 
            type = "integer"), MinUpdatePeriodSeconds = structure(logical(0), 
            locationName = "minUpdatePeriodSeconds", shape = "__integer", 
            type = "integer"), PeriodTriggers = structure(list(structure(logical(0), 
            shape = "__PeriodTriggersElement", type = "string")), 
            locationName = "periodTriggers", shape = "__listOf__PeriodTriggersElement", 
            type = "list"), Profile = structure(logical(0), locationName = "profile", 
            shape = "Profile", type = "string"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure"), SuggestedPresentationDelaySeconds = structure(logical(0), 
            locationName = "suggestedPresentationDelaySeconds", 
            shape = "__integer", type = "integer")), locationName = "dashPackage", 
            shape = "DashPackage", type = "structure"), Description = structure(logical(0), 
            locationName = "description", shape = "__string", 
            type = "string"), HlsPackage = structure(list(AdMarkers = structure(logical(0), 
            locationName = "adMarkers", shape = "AdMarkers", 
            type = "string"), Encryption = structure(list(ConstantInitializationVector = structure(logical(0), 
            locationName = "constantInitializationVector", shape = "__string", 
            type = "string"), EncryptionMethod = structure(logical(0), 
            locationName = "encryptionMethod", shape = "EncryptionMethod", 
            type = "string"), KeyRotationIntervalSeconds = structure(logical(0), 
            locationName = "keyRotationIntervalSeconds", shape = "__integer", 
            type = "integer"), RepeatExtXKey = structure(logical(0), 
            locationName = "repeatExtXKey", shape = "__boolean", 
            type = "boolean"), SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "HlsEncryption", type = "structure"), IncludeIframeOnlyStream = structure(logical(0), 
            locationName = "includeIframeOnlyStream", shape = "__boolean", 
            type = "boolean"), PlaylistType = structure(logical(0), 
            locationName = "playlistType", shape = "PlaylistType", 
            type = "string"), PlaylistWindowSeconds = structure(logical(0), 
            locationName = "playlistWindowSeconds", shape = "__integer", 
            type = "integer"), ProgramDateTimeIntervalSeconds = structure(logical(0), 
            locationName = "programDateTimeIntervalSeconds", 
            shape = "__integer", type = "integer"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure"), UseAudioRenditionGroup = structure(logical(0), 
            locationName = "useAudioRenditionGroup", shape = "__boolean", 
            type = "boolean")), locationName = "hlsPackage", 
            shape = "HlsPackage", type = "structure"), Id = structure(logical(0), 
            locationName = "id", shape = "__string", type = "string"), 
        ManifestName = structure(logical(0), locationName = "manifestName", 
            shape = "__string", type = "string"), MssPackage = structure(list(Encryption = structure(list(SpekeKeyProvider = structure(list(ResourceId = structure(logical(0), 
            locationName = "resourceId", shape = "__string", 
            type = "string"), RoleArn = structure(logical(0), 
            locationName = "roleArn", shape = "__string", type = "string"), 
            SystemIds = structure(list(structure(logical(0), 
                shape = "__string", type = "string")), locationName = "systemIds", 
                shape = "__listOf__string", type = "list"), Url = structure(logical(0), 
                locationName = "url", shape = "__string", type = "string")), 
            locationName = "spekeKeyProvider", shape = "SpekeKeyProvider", 
            type = "structure")), locationName = "encryption", 
            shape = "MssEncryption", type = "structure"), ManifestWindowSeconds = structure(logical(0), 
            locationName = "manifestWindowSeconds", shape = "__integer", 
            type = "integer"), SegmentDurationSeconds = structure(logical(0), 
            locationName = "segmentDurationSeconds", shape = "__integer", 
            type = "integer"), StreamSelection = structure(list(MaxVideoBitsPerSecond = structure(logical(0), 
            locationName = "maxVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), MinVideoBitsPerSecond = structure(logical(0), 
            locationName = "minVideoBitsPerSecond", shape = "__integer", 
            type = "integer"), StreamOrder = structure(logical(0), 
            locationName = "streamOrder", shape = "StreamOrder", 
            type = "string")), locationName = "streamSelection", 
            shape = "StreamSelection", type = "structure")), 
            locationName = "mssPackage", shape = "MssPackage", 
            type = "structure"), StartoverWindowSeconds = structure(logical(0), 
            locationName = "startoverWindowSeconds", shape = "__integer", 
            type = "integer"), TimeDelaySeconds = structure(logical(0), 
            locationName = "timeDelaySeconds", shape = "__integer", 
            type = "integer"), Url = structure(logical(0), locationName = "url", 
            shape = "__string", type = "string"), Whitelist = structure(list(structure(logical(0), 
            shape = "__string", type = "string")), locationName = "whitelist", 
            shape = "__listOf__string", type = "list")), shape = "UpdateOriginEndpointResponse", 
        type = "structure")
    return(populate(args, shape))
}
