create_delivery_stream_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(DeliveryStreamName = structure(logical(0), 
        shape = "DeliveryStreamName", type = "string", max = 64L, 
        min = 1L, pattern = "[a-zA-Z0-9_.-]+"), DeliveryStreamType = structure(logical(0), 
        shape = "DeliveryStreamType", type = "string"), KinesisStreamSourceConfiguration = structure(list(KinesisStreamARN = structure(logical(0), 
        shape = "KinesisStreamARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*"), RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*")), shape = "KinesisStreamSourceConfiguration", 
        type = "structure"), S3DestinationConfiguration = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), BucketARN = structure(logical(0), 
        shape = "BucketARN", type = "string", max = 2048L, min = 1L, 
        pattern = "arn:.*"), Prefix = structure(logical(0), shape = "Prefix", 
        type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
        shape = "SizeInMBs", type = "integer", max = 128L, min = 1L), 
        IntervalInSeconds = structure(logical(0), shape = "IntervalInSeconds", 
            type = "integer", max = 900L, min = 60L)), shape = "BufferingHints", 
        type = "structure"), CompressionFormat = structure(logical(0), 
        shape = "CompressionFormat", type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
        shape = "NoEncryptionConfig", type = "string"), KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
        shape = "AWSKMSKeyARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
        type = "structure")), shape = "EncryptionConfiguration", 
        type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
        shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
        shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
        type = "structure")), shape = "S3DestinationConfiguration", 
        deprecated = TRUE, type = "structure"), ExtendedS3DestinationConfiguration = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), BucketARN = structure(logical(0), 
        shape = "BucketARN", type = "string", max = 2048L, min = 1L, 
        pattern = "arn:.*"), Prefix = structure(logical(0), shape = "Prefix", 
        type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
        shape = "SizeInMBs", type = "integer", max = 128L, min = 1L), 
        IntervalInSeconds = structure(logical(0), shape = "IntervalInSeconds", 
            type = "integer", max = 900L, min = 60L)), shape = "BufferingHints", 
        type = "structure"), CompressionFormat = structure(logical(0), 
        shape = "CompressionFormat", type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
        shape = "NoEncryptionConfig", type = "string"), KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
        shape = "AWSKMSKeyARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
        type = "structure")), shape = "EncryptionConfiguration", 
        type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
        shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
        shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
        type = "structure"), ProcessingConfiguration = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), Processors = structure(list(structure(list(Type = structure(logical(0), 
        shape = "ProcessorType", type = "string"), Parameters = structure(list(structure(list(ParameterName = structure(logical(0), 
        shape = "ProcessorParameterName", type = "string"), ParameterValue = structure(logical(0), 
        shape = "ProcessorParameterValue", type = "string", max = 512L, 
        min = 1L)), shape = "ProcessorParameter", type = "structure")), 
        shape = "ProcessorParameterList", type = "list")), shape = "Processor", 
        type = "structure")), shape = "ProcessorList", type = "list")), 
        shape = "ProcessingConfiguration", type = "structure"), 
        S3BackupMode = structure(logical(0), shape = "S3BackupMode", 
            type = "string"), S3BackupConfiguration = structure(list(RoleARN = structure(logical(0), 
            shape = "RoleARN", type = "string", max = 512L, min = 1L, 
            pattern = "arn:.*"), BucketARN = structure(logical(0), 
            shape = "BucketARN", type = "string", max = 2048L, 
            min = 1L, pattern = "arn:.*"), Prefix = structure(logical(0), 
            shape = "Prefix", type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
            shape = "SizeInMBs", type = "integer", max = 128L, 
            min = 1L), IntervalInSeconds = structure(logical(0), 
            shape = "IntervalInSeconds", type = "integer", max = 900L, 
            min = 60L)), shape = "BufferingHints", type = "structure"), 
            CompressionFormat = structure(logical(0), shape = "CompressionFormat", 
                type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
                shape = "NoEncryptionConfig", type = "string"), 
                KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
                  shape = "AWSKMSKeyARN", type = "string", max = 512L, 
                  min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
                  type = "structure")), shape = "EncryptionConfiguration", 
                type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
                shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
                shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
                type = "structure")), shape = "S3DestinationConfiguration", 
            type = "structure"), DataFormatConversionConfiguration = structure(list(SchemaConfiguration = structure(list(RoleARN = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), CatalogId = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), DatabaseName = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), TableName = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), Region = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), VersionId = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$")), shape = "SchemaConfiguration", 
            type = "structure"), InputFormatConfiguration = structure(list(Deserializer = structure(list(OpenXJsonSerDe = structure(list(ConvertDotsInJsonKeysToUnderscores = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), CaseInsensitive = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), ColumnToJsonKeyMappings = structure(list(structure(logical(0), 
            shape = "NonEmptyString", type = "string", pattern = "^(?!\\s*$).+")), 
            shape = "ColumnToJsonKeyMappings", type = "map")), 
            shape = "OpenXJsonSerDe", type = "structure"), HiveJsonSerDe = structure(list(TimestampFormats = structure(list(structure(logical(0), 
            shape = "NonEmptyString", type = "string", pattern = "^(?!\\s*$).+")), 
            shape = "ListOfNonEmptyStrings", type = "list")), 
            shape = "HiveJsonSerDe", type = "structure")), shape = "Deserializer", 
            type = "structure")), shape = "InputFormatConfiguration", 
            type = "structure"), OutputFormatConfiguration = structure(list(Serializer = structure(list(ParquetSerDe = structure(list(BlockSizeBytes = structure(logical(0), 
            shape = "BlockSizeBytes", type = "integer", min = 67108864L), 
            PageSizeBytes = structure(logical(0), shape = "ParquetPageSizeBytes", 
                type = "integer", min = 65536L), Compression = structure(logical(0), 
                shape = "ParquetCompression", type = "string"), 
            EnableDictionaryCompression = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), MaxPaddingBytes = structure(logical(0), 
                shape = "NonNegativeIntegerObject", type = "integer", 
                min = 0L), WriterVersion = structure(logical(0), 
                shape = "ParquetWriterVersion", type = "string")), 
            shape = "ParquetSerDe", type = "structure"), OrcSerDe = structure(list(StripeSizeBytes = structure(logical(0), 
            shape = "OrcStripeSizeBytes", type = "integer", min = 8388608L), 
            BlockSizeBytes = structure(logical(0), shape = "BlockSizeBytes", 
                type = "integer", min = 67108864L), RowIndexStride = structure(logical(0), 
                shape = "OrcRowIndexStride", type = "integer", 
                min = 1000L), EnablePadding = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), PaddingTolerance = structure(logical(0), 
                shape = "Proportion", type = "double", max = 1L, 
                min = 0L), Compression = structure(logical(0), 
                shape = "OrcCompression", type = "string"), BloomFilterColumns = structure(list(structure(logical(0), 
                shape = "NonEmptyStringWithoutWhitespace", type = "string", 
                pattern = "^\\S+$")), shape = "ListOfNonEmptyStringsWithoutWhitespace", 
                type = "list"), BloomFilterFalsePositiveProbability = structure(logical(0), 
                shape = "Proportion", type = "double", max = 1L, 
                min = 0L), DictionaryKeyThreshold = structure(logical(0), 
                shape = "Proportion", type = "double", max = 1L, 
                min = 0L), FormatVersion = structure(logical(0), 
                shape = "OrcFormatVersion", type = "string")), 
            shape = "OrcSerDe", type = "structure")), shape = "Serializer", 
            type = "structure")), shape = "OutputFormatConfiguration", 
            type = "structure"), Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean")), shape = "DataFormatConversionConfiguration", 
            type = "structure")), shape = "ExtendedS3DestinationConfiguration", 
        type = "structure"), RedshiftDestinationConfiguration = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), ClusterJDBCURL = structure(logical(0), 
        shape = "ClusterJDBCURL", type = "string", min = 1L, 
        pattern = "jdbc:(redshift|postgresql)://((?!-)[A-Za-z0-9-]{1,63}(?<!-)\\.)+redshift\\.amazonaws\\.com:\\d{1,5}/[a-zA-Z0-9_$]+"), 
        CopyCommand = structure(list(DataTableName = structure(logical(0), 
            shape = "DataTableName", type = "string", min = 1L), 
            DataTableColumns = structure(logical(0), shape = "DataTableColumns", 
                type = "string"), CopyOptions = structure(logical(0), 
                shape = "CopyOptions", type = "string")), shape = "CopyCommand", 
            type = "structure"), Username = structure(logical(0), 
            shape = "Username", type = "string", min = 1L, sensitive = TRUE), 
        Password = structure(logical(0), shape = "Password", 
            type = "string", min = 6L, sensitive = TRUE), RetryOptions = structure(list(DurationInSeconds = structure(logical(0), 
            shape = "RedshiftRetryDurationInSeconds", type = "integer", 
            max = 7200L, min = 0L)), shape = "RedshiftRetryOptions", 
            type = "structure"), S3Configuration = structure(list(RoleARN = structure(logical(0), 
            shape = "RoleARN", type = "string", max = 512L, min = 1L, 
            pattern = "arn:.*"), BucketARN = structure(logical(0), 
            shape = "BucketARN", type = "string", max = 2048L, 
            min = 1L, pattern = "arn:.*"), Prefix = structure(logical(0), 
            shape = "Prefix", type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
            shape = "SizeInMBs", type = "integer", max = 128L, 
            min = 1L), IntervalInSeconds = structure(logical(0), 
            shape = "IntervalInSeconds", type = "integer", max = 900L, 
            min = 60L)), shape = "BufferingHints", type = "structure"), 
            CompressionFormat = structure(logical(0), shape = "CompressionFormat", 
                type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
                shape = "NoEncryptionConfig", type = "string"), 
                KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
                  shape = "AWSKMSKeyARN", type = "string", max = 512L, 
                  min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
                  type = "structure")), shape = "EncryptionConfiguration", 
                type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
                shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
                shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
                type = "structure")), shape = "S3DestinationConfiguration", 
            type = "structure"), ProcessingConfiguration = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), Processors = structure(list(structure(list(Type = structure(logical(0), 
            shape = "ProcessorType", type = "string"), Parameters = structure(list(structure(list(ParameterName = structure(logical(0), 
            shape = "ProcessorParameterName", type = "string"), 
            ParameterValue = structure(logical(0), shape = "ProcessorParameterValue", 
                type = "string", max = 512L, min = 1L)), shape = "ProcessorParameter", 
            type = "structure")), shape = "ProcessorParameterList", 
            type = "list")), shape = "Processor", type = "structure")), 
            shape = "ProcessorList", type = "list")), shape = "ProcessingConfiguration", 
            type = "structure"), S3BackupMode = structure(logical(0), 
            shape = "RedshiftS3BackupMode", type = "string"), 
        S3BackupConfiguration = structure(list(RoleARN = structure(logical(0), 
            shape = "RoleARN", type = "string", max = 512L, min = 1L, 
            pattern = "arn:.*"), BucketARN = structure(logical(0), 
            shape = "BucketARN", type = "string", max = 2048L, 
            min = 1L, pattern = "arn:.*"), Prefix = structure(logical(0), 
            shape = "Prefix", type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
            shape = "SizeInMBs", type = "integer", max = 128L, 
            min = 1L), IntervalInSeconds = structure(logical(0), 
            shape = "IntervalInSeconds", type = "integer", max = 900L, 
            min = 60L)), shape = "BufferingHints", type = "structure"), 
            CompressionFormat = structure(logical(0), shape = "CompressionFormat", 
                type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
                shape = "NoEncryptionConfig", type = "string"), 
                KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
                  shape = "AWSKMSKeyARN", type = "string", max = 512L, 
                  min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
                  type = "structure")), shape = "EncryptionConfiguration", 
                type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
                shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
                shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
                type = "structure")), shape = "S3DestinationConfiguration", 
            type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
            shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
            shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
            type = "structure")), shape = "RedshiftDestinationConfiguration", 
        type = "structure"), ElasticsearchDestinationConfiguration = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), DomainARN = structure(logical(0), 
        shape = "ElasticsearchDomainARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*"), IndexName = structure(logical(0), 
        shape = "ElasticsearchIndexName", type = "string", max = 80L, 
        min = 1L), TypeName = structure(logical(0), shape = "ElasticsearchTypeName", 
        type = "string", max = 100L, min = 1L), IndexRotationPeriod = structure(logical(0), 
        shape = "ElasticsearchIndexRotationPeriod", type = "string"), 
        BufferingHints = structure(list(IntervalInSeconds = structure(logical(0), 
            shape = "ElasticsearchBufferingIntervalInSeconds", 
            type = "integer", max = 900L, min = 60L), SizeInMBs = structure(logical(0), 
            shape = "ElasticsearchBufferingSizeInMBs", type = "integer", 
            max = 100L, min = 1L)), shape = "ElasticsearchBufferingHints", 
            type = "structure"), RetryOptions = structure(list(DurationInSeconds = structure(logical(0), 
            shape = "ElasticsearchRetryDurationInSeconds", type = "integer", 
            max = 7200L, min = 0L)), shape = "ElasticsearchRetryOptions", 
            type = "structure"), S3BackupMode = structure(logical(0), 
            shape = "ElasticsearchS3BackupMode", type = "string"), 
        S3Configuration = structure(list(RoleARN = structure(logical(0), 
            shape = "RoleARN", type = "string", max = 512L, min = 1L, 
            pattern = "arn:.*"), BucketARN = structure(logical(0), 
            shape = "BucketARN", type = "string", max = 2048L, 
            min = 1L, pattern = "arn:.*"), Prefix = structure(logical(0), 
            shape = "Prefix", type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
            shape = "SizeInMBs", type = "integer", max = 128L, 
            min = 1L), IntervalInSeconds = structure(logical(0), 
            shape = "IntervalInSeconds", type = "integer", max = 900L, 
            min = 60L)), shape = "BufferingHints", type = "structure"), 
            CompressionFormat = structure(logical(0), shape = "CompressionFormat", 
                type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
                shape = "NoEncryptionConfig", type = "string"), 
                KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
                  shape = "AWSKMSKeyARN", type = "string", max = 512L, 
                  min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
                  type = "structure")), shape = "EncryptionConfiguration", 
                type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
                shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
                shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
                type = "structure")), shape = "S3DestinationConfiguration", 
            type = "structure"), ProcessingConfiguration = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), Processors = structure(list(structure(list(Type = structure(logical(0), 
            shape = "ProcessorType", type = "string"), Parameters = structure(list(structure(list(ParameterName = structure(logical(0), 
            shape = "ProcessorParameterName", type = "string"), 
            ParameterValue = structure(logical(0), shape = "ProcessorParameterValue", 
                type = "string", max = 512L, min = 1L)), shape = "ProcessorParameter", 
            type = "structure")), shape = "ProcessorParameterList", 
            type = "list")), shape = "Processor", type = "structure")), 
            shape = "ProcessorList", type = "list")), shape = "ProcessingConfiguration", 
            type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
            shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
            shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
            type = "structure")), shape = "ElasticsearchDestinationConfiguration", 
        type = "structure"), SplunkDestinationConfiguration = structure(list(HECEndpoint = structure(logical(0), 
        shape = "HECEndpoint", type = "string"), HECEndpointType = structure(logical(0), 
        shape = "HECEndpointType", type = "string"), HECToken = structure(logical(0), 
        shape = "HECToken", type = "string"), HECAcknowledgmentTimeoutInSeconds = structure(logical(0), 
        shape = "HECAcknowledgmentTimeoutInSeconds", type = "integer", 
        max = 600L, min = 180L), RetryOptions = structure(list(DurationInSeconds = structure(logical(0), 
        shape = "SplunkRetryDurationInSeconds", type = "integer", 
        max = 7200L, min = 0L)), shape = "SplunkRetryOptions", 
        type = "structure"), S3BackupMode = structure(logical(0), 
        shape = "SplunkS3BackupMode", type = "string"), S3Configuration = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), BucketARN = structure(logical(0), 
        shape = "BucketARN", type = "string", max = 2048L, min = 1L, 
        pattern = "arn:.*"), Prefix = structure(logical(0), shape = "Prefix", 
        type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
        shape = "SizeInMBs", type = "integer", max = 128L, min = 1L), 
        IntervalInSeconds = structure(logical(0), shape = "IntervalInSeconds", 
            type = "integer", max = 900L, min = 60L)), shape = "BufferingHints", 
        type = "structure"), CompressionFormat = structure(logical(0), 
        shape = "CompressionFormat", type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
        shape = "NoEncryptionConfig", type = "string"), KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
        shape = "AWSKMSKeyARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
        type = "structure")), shape = "EncryptionConfiguration", 
        type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
        shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
        shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
        type = "structure")), shape = "S3DestinationConfiguration", 
        type = "structure"), ProcessingConfiguration = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), Processors = structure(list(structure(list(Type = structure(logical(0), 
        shape = "ProcessorType", type = "string"), Parameters = structure(list(structure(list(ParameterName = structure(logical(0), 
        shape = "ProcessorParameterName", type = "string"), ParameterValue = structure(logical(0), 
        shape = "ProcessorParameterValue", type = "string", max = 512L, 
        min = 1L)), shape = "ProcessorParameter", type = "structure")), 
        shape = "ProcessorParameterList", type = "list")), shape = "Processor", 
        type = "structure")), shape = "ProcessorList", type = "list")), 
        shape = "ProcessingConfiguration", type = "structure"), 
        CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
            shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
            shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
            type = "structure")), shape = "SplunkDestinationConfiguration", 
        type = "structure")), shape = "CreateDeliveryStreamInput", 
        type = "structure")
    return(populate(args, shape))
}

create_delivery_stream_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(DeliveryStreamARN = structure(logical(0), 
        shape = "DeliveryStreamARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*")), shape = "CreateDeliveryStreamOutput", 
        type = "structure")
    return(populate(args, shape))
}

delete_delivery_stream_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(DeliveryStreamName = structure(logical(0), 
        shape = "DeliveryStreamName", type = "string", max = 64L, 
        min = 1L, pattern = "[a-zA-Z0-9_.-]+")), shape = "DeleteDeliveryStreamInput", 
        type = "structure")
    return(populate(args, shape))
}

delete_delivery_stream_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(), shape = "DeleteDeliveryStreamOutput", 
        type = "structure")
    return(populate(args, shape))
}

describe_delivery_stream_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(DeliveryStreamName = structure(logical(0), 
        shape = "DeliveryStreamName", type = "string", max = 64L, 
        min = 1L, pattern = "[a-zA-Z0-9_.-]+"), Limit = structure(logical(0), 
        shape = "DescribeDeliveryStreamInputLimit", type = "integer", 
        max = 10000L, min = 1L), ExclusiveStartDestinationId = structure(logical(0), 
        shape = "DestinationId", type = "string", max = 100L, 
        min = 1L)), shape = "DescribeDeliveryStreamInput", type = "structure")
    return(populate(args, shape))
}

describe_delivery_stream_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(DeliveryStreamDescription = structure(list(DeliveryStreamName = structure(logical(0), 
        shape = "DeliveryStreamName", type = "string", max = 64L, 
        min = 1L, pattern = "[a-zA-Z0-9_.-]+"), DeliveryStreamARN = structure(logical(0), 
        shape = "DeliveryStreamARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*"), DeliveryStreamStatus = structure(logical(0), 
        shape = "DeliveryStreamStatus", type = "string"), DeliveryStreamType = structure(logical(0), 
        shape = "DeliveryStreamType", type = "string"), VersionId = structure(logical(0), 
        shape = "DeliveryStreamVersionId", type = "string", max = 50L, 
        min = 1L, pattern = "[0-9]+"), CreateTimestamp = structure(logical(0), 
        shape = "Timestamp", type = "timestamp"), LastUpdateTimestamp = structure(logical(0), 
        shape = "Timestamp", type = "timestamp"), Source = structure(list(KinesisStreamSourceDescription = structure(list(KinesisStreamARN = structure(logical(0), 
        shape = "KinesisStreamARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*"), RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), DeliveryStartTimestamp = structure(logical(0), 
        shape = "DeliveryStartTimestamp", type = "timestamp")), 
        shape = "KinesisStreamSourceDescription", type = "structure")), 
        shape = "SourceDescription", type = "structure"), Destinations = structure(list(structure(list(DestinationId = structure(logical(0), 
        shape = "DestinationId", type = "string", max = 100L, 
        min = 1L), S3DestinationDescription = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), BucketARN = structure(logical(0), 
        shape = "BucketARN", type = "string", max = 2048L, min = 1L, 
        pattern = "arn:.*"), Prefix = structure(logical(0), shape = "Prefix", 
        type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
        shape = "SizeInMBs", type = "integer", max = 128L, min = 1L), 
        IntervalInSeconds = structure(logical(0), shape = "IntervalInSeconds", 
            type = "integer", max = 900L, min = 60L)), shape = "BufferingHints", 
        type = "structure"), CompressionFormat = structure(logical(0), 
        shape = "CompressionFormat", type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
        shape = "NoEncryptionConfig", type = "string"), KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
        shape = "AWSKMSKeyARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
        type = "structure")), shape = "EncryptionConfiguration", 
        type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
        shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
        shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
        type = "structure")), shape = "S3DestinationDescription", 
        type = "structure"), ExtendedS3DestinationDescription = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), BucketARN = structure(logical(0), 
        shape = "BucketARN", type = "string", max = 2048L, min = 1L, 
        pattern = "arn:.*"), Prefix = structure(logical(0), shape = "Prefix", 
        type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
        shape = "SizeInMBs", type = "integer", max = 128L, min = 1L), 
        IntervalInSeconds = structure(logical(0), shape = "IntervalInSeconds", 
            type = "integer", max = 900L, min = 60L)), shape = "BufferingHints", 
        type = "structure"), CompressionFormat = structure(logical(0), 
        shape = "CompressionFormat", type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
        shape = "NoEncryptionConfig", type = "string"), KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
        shape = "AWSKMSKeyARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
        type = "structure")), shape = "EncryptionConfiguration", 
        type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
        shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
        shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
        type = "structure"), ProcessingConfiguration = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), Processors = structure(list(structure(list(Type = structure(logical(0), 
        shape = "ProcessorType", type = "string"), Parameters = structure(list(structure(list(ParameterName = structure(logical(0), 
        shape = "ProcessorParameterName", type = "string"), ParameterValue = structure(logical(0), 
        shape = "ProcessorParameterValue", type = "string", max = 512L, 
        min = 1L)), shape = "ProcessorParameter", type = "structure")), 
        shape = "ProcessorParameterList", type = "list")), shape = "Processor", 
        type = "structure")), shape = "ProcessorList", type = "list")), 
        shape = "ProcessingConfiguration", type = "structure"), 
        S3BackupMode = structure(logical(0), shape = "S3BackupMode", 
            type = "string"), S3BackupDescription = structure(list(RoleARN = structure(logical(0), 
            shape = "RoleARN", type = "string", max = 512L, min = 1L, 
            pattern = "arn:.*"), BucketARN = structure(logical(0), 
            shape = "BucketARN", type = "string", max = 2048L, 
            min = 1L, pattern = "arn:.*"), Prefix = structure(logical(0), 
            shape = "Prefix", type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
            shape = "SizeInMBs", type = "integer", max = 128L, 
            min = 1L), IntervalInSeconds = structure(logical(0), 
            shape = "IntervalInSeconds", type = "integer", max = 900L, 
            min = 60L)), shape = "BufferingHints", type = "structure"), 
            CompressionFormat = structure(logical(0), shape = "CompressionFormat", 
                type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
                shape = "NoEncryptionConfig", type = "string"), 
                KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
                  shape = "AWSKMSKeyARN", type = "string", max = 512L, 
                  min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
                  type = "structure")), shape = "EncryptionConfiguration", 
                type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
                shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
                shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
                type = "structure")), shape = "S3DestinationDescription", 
            type = "structure"), DataFormatConversionConfiguration = structure(list(SchemaConfiguration = structure(list(RoleARN = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), CatalogId = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), DatabaseName = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), TableName = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), Region = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), VersionId = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$")), shape = "SchemaConfiguration", 
            type = "structure"), InputFormatConfiguration = structure(list(Deserializer = structure(list(OpenXJsonSerDe = structure(list(ConvertDotsInJsonKeysToUnderscores = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), CaseInsensitive = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), ColumnToJsonKeyMappings = structure(list(structure(logical(0), 
            shape = "NonEmptyString", type = "string", pattern = "^(?!\\s*$).+")), 
            shape = "ColumnToJsonKeyMappings", type = "map")), 
            shape = "OpenXJsonSerDe", type = "structure"), HiveJsonSerDe = structure(list(TimestampFormats = structure(list(structure(logical(0), 
            shape = "NonEmptyString", type = "string", pattern = "^(?!\\s*$).+")), 
            shape = "ListOfNonEmptyStrings", type = "list")), 
            shape = "HiveJsonSerDe", type = "structure")), shape = "Deserializer", 
            type = "structure")), shape = "InputFormatConfiguration", 
            type = "structure"), OutputFormatConfiguration = structure(list(Serializer = structure(list(ParquetSerDe = structure(list(BlockSizeBytes = structure(logical(0), 
            shape = "BlockSizeBytes", type = "integer", min = 67108864L), 
            PageSizeBytes = structure(logical(0), shape = "ParquetPageSizeBytes", 
                type = "integer", min = 65536L), Compression = structure(logical(0), 
                shape = "ParquetCompression", type = "string"), 
            EnableDictionaryCompression = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), MaxPaddingBytes = structure(logical(0), 
                shape = "NonNegativeIntegerObject", type = "integer", 
                min = 0L), WriterVersion = structure(logical(0), 
                shape = "ParquetWriterVersion", type = "string")), 
            shape = "ParquetSerDe", type = "structure"), OrcSerDe = structure(list(StripeSizeBytes = structure(logical(0), 
            shape = "OrcStripeSizeBytes", type = "integer", min = 8388608L), 
            BlockSizeBytes = structure(logical(0), shape = "BlockSizeBytes", 
                type = "integer", min = 67108864L), RowIndexStride = structure(logical(0), 
                shape = "OrcRowIndexStride", type = "integer", 
                min = 1000L), EnablePadding = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), PaddingTolerance = structure(logical(0), 
                shape = "Proportion", type = "double", max = 1L, 
                min = 0L), Compression = structure(logical(0), 
                shape = "OrcCompression", type = "string"), BloomFilterColumns = structure(list(structure(logical(0), 
                shape = "NonEmptyStringWithoutWhitespace", type = "string", 
                pattern = "^\\S+$")), shape = "ListOfNonEmptyStringsWithoutWhitespace", 
                type = "list"), BloomFilterFalsePositiveProbability = structure(logical(0), 
                shape = "Proportion", type = "double", max = 1L, 
                min = 0L), DictionaryKeyThreshold = structure(logical(0), 
                shape = "Proportion", type = "double", max = 1L, 
                min = 0L), FormatVersion = structure(logical(0), 
                shape = "OrcFormatVersion", type = "string")), 
            shape = "OrcSerDe", type = "structure")), shape = "Serializer", 
            type = "structure")), shape = "OutputFormatConfiguration", 
            type = "structure"), Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean")), shape = "DataFormatConversionConfiguration", 
            type = "structure")), shape = "ExtendedS3DestinationDescription", 
        type = "structure"), RedshiftDestinationDescription = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), ClusterJDBCURL = structure(logical(0), 
        shape = "ClusterJDBCURL", type = "string", min = 1L, 
        pattern = "jdbc:(redshift|postgresql)://((?!-)[A-Za-z0-9-]{1,63}(?<!-)\\.)+redshift\\.amazonaws\\.com:\\d{1,5}/[a-zA-Z0-9_$]+"), 
        CopyCommand = structure(list(DataTableName = structure(logical(0), 
            shape = "DataTableName", type = "string", min = 1L), 
            DataTableColumns = structure(logical(0), shape = "DataTableColumns", 
                type = "string"), CopyOptions = structure(logical(0), 
                shape = "CopyOptions", type = "string")), shape = "CopyCommand", 
            type = "structure"), Username = structure(logical(0), 
            shape = "Username", type = "string", min = 1L, sensitive = TRUE), 
        RetryOptions = structure(list(DurationInSeconds = structure(logical(0), 
            shape = "RedshiftRetryDurationInSeconds", type = "integer", 
            max = 7200L, min = 0L)), shape = "RedshiftRetryOptions", 
            type = "structure"), S3DestinationDescription = structure(list(RoleARN = structure(logical(0), 
            shape = "RoleARN", type = "string", max = 512L, min = 1L, 
            pattern = "arn:.*"), BucketARN = structure(logical(0), 
            shape = "BucketARN", type = "string", max = 2048L, 
            min = 1L, pattern = "arn:.*"), Prefix = structure(logical(0), 
            shape = "Prefix", type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
            shape = "SizeInMBs", type = "integer", max = 128L, 
            min = 1L), IntervalInSeconds = structure(logical(0), 
            shape = "IntervalInSeconds", type = "integer", max = 900L, 
            min = 60L)), shape = "BufferingHints", type = "structure"), 
            CompressionFormat = structure(logical(0), shape = "CompressionFormat", 
                type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
                shape = "NoEncryptionConfig", type = "string"), 
                KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
                  shape = "AWSKMSKeyARN", type = "string", max = 512L, 
                  min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
                  type = "structure")), shape = "EncryptionConfiguration", 
                type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
                shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
                shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
                type = "structure")), shape = "S3DestinationDescription", 
            type = "structure"), ProcessingConfiguration = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), Processors = structure(list(structure(list(Type = structure(logical(0), 
            shape = "ProcessorType", type = "string"), Parameters = structure(list(structure(list(ParameterName = structure(logical(0), 
            shape = "ProcessorParameterName", type = "string"), 
            ParameterValue = structure(logical(0), shape = "ProcessorParameterValue", 
                type = "string", max = 512L, min = 1L)), shape = "ProcessorParameter", 
            type = "structure")), shape = "ProcessorParameterList", 
            type = "list")), shape = "Processor", type = "structure")), 
            shape = "ProcessorList", type = "list")), shape = "ProcessingConfiguration", 
            type = "structure"), S3BackupMode = structure(logical(0), 
            shape = "RedshiftS3BackupMode", type = "string"), 
        S3BackupDescription = structure(list(RoleARN = structure(logical(0), 
            shape = "RoleARN", type = "string", max = 512L, min = 1L, 
            pattern = "arn:.*"), BucketARN = structure(logical(0), 
            shape = "BucketARN", type = "string", max = 2048L, 
            min = 1L, pattern = "arn:.*"), Prefix = structure(logical(0), 
            shape = "Prefix", type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
            shape = "SizeInMBs", type = "integer", max = 128L, 
            min = 1L), IntervalInSeconds = structure(logical(0), 
            shape = "IntervalInSeconds", type = "integer", max = 900L, 
            min = 60L)), shape = "BufferingHints", type = "structure"), 
            CompressionFormat = structure(logical(0), shape = "CompressionFormat", 
                type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
                shape = "NoEncryptionConfig", type = "string"), 
                KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
                  shape = "AWSKMSKeyARN", type = "string", max = 512L, 
                  min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
                  type = "structure")), shape = "EncryptionConfiguration", 
                type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
                shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
                shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
                type = "structure")), shape = "S3DestinationDescription", 
            type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
            shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
            shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
            type = "structure")), shape = "RedshiftDestinationDescription", 
        type = "structure"), ElasticsearchDestinationDescription = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), DomainARN = structure(logical(0), 
        shape = "ElasticsearchDomainARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*"), IndexName = structure(logical(0), 
        shape = "ElasticsearchIndexName", type = "string", max = 80L, 
        min = 1L), TypeName = structure(logical(0), shape = "ElasticsearchTypeName", 
        type = "string", max = 100L, min = 1L), IndexRotationPeriod = structure(logical(0), 
        shape = "ElasticsearchIndexRotationPeriod", type = "string"), 
        BufferingHints = structure(list(IntervalInSeconds = structure(logical(0), 
            shape = "ElasticsearchBufferingIntervalInSeconds", 
            type = "integer", max = 900L, min = 60L), SizeInMBs = structure(logical(0), 
            shape = "ElasticsearchBufferingSizeInMBs", type = "integer", 
            max = 100L, min = 1L)), shape = "ElasticsearchBufferingHints", 
            type = "structure"), RetryOptions = structure(list(DurationInSeconds = structure(logical(0), 
            shape = "ElasticsearchRetryDurationInSeconds", type = "integer", 
            max = 7200L, min = 0L)), shape = "ElasticsearchRetryOptions", 
            type = "structure"), S3BackupMode = structure(logical(0), 
            shape = "ElasticsearchS3BackupMode", type = "string"), 
        S3DestinationDescription = structure(list(RoleARN = structure(logical(0), 
            shape = "RoleARN", type = "string", max = 512L, min = 1L, 
            pattern = "arn:.*"), BucketARN = structure(logical(0), 
            shape = "BucketARN", type = "string", max = 2048L, 
            min = 1L, pattern = "arn:.*"), Prefix = structure(logical(0), 
            shape = "Prefix", type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
            shape = "SizeInMBs", type = "integer", max = 128L, 
            min = 1L), IntervalInSeconds = structure(logical(0), 
            shape = "IntervalInSeconds", type = "integer", max = 900L, 
            min = 60L)), shape = "BufferingHints", type = "structure"), 
            CompressionFormat = structure(logical(0), shape = "CompressionFormat", 
                type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
                shape = "NoEncryptionConfig", type = "string"), 
                KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
                  shape = "AWSKMSKeyARN", type = "string", max = 512L, 
                  min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
                  type = "structure")), shape = "EncryptionConfiguration", 
                type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
                shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
                shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
                type = "structure")), shape = "S3DestinationDescription", 
            type = "structure"), ProcessingConfiguration = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), Processors = structure(list(structure(list(Type = structure(logical(0), 
            shape = "ProcessorType", type = "string"), Parameters = structure(list(structure(list(ParameterName = structure(logical(0), 
            shape = "ProcessorParameterName", type = "string"), 
            ParameterValue = structure(logical(0), shape = "ProcessorParameterValue", 
                type = "string", max = 512L, min = 1L)), shape = "ProcessorParameter", 
            type = "structure")), shape = "ProcessorParameterList", 
            type = "list")), shape = "Processor", type = "structure")), 
            shape = "ProcessorList", type = "list")), shape = "ProcessingConfiguration", 
            type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
            shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
            shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
            type = "structure")), shape = "ElasticsearchDestinationDescription", 
        type = "structure"), SplunkDestinationDescription = structure(list(HECEndpoint = structure(logical(0), 
        shape = "HECEndpoint", type = "string"), HECEndpointType = structure(logical(0), 
        shape = "HECEndpointType", type = "string"), HECToken = structure(logical(0), 
        shape = "HECToken", type = "string"), HECAcknowledgmentTimeoutInSeconds = structure(logical(0), 
        shape = "HECAcknowledgmentTimeoutInSeconds", type = "integer", 
        max = 600L, min = 180L), RetryOptions = structure(list(DurationInSeconds = structure(logical(0), 
        shape = "SplunkRetryDurationInSeconds", type = "integer", 
        max = 7200L, min = 0L)), shape = "SplunkRetryOptions", 
        type = "structure"), S3BackupMode = structure(logical(0), 
        shape = "SplunkS3BackupMode", type = "string"), S3DestinationDescription = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), BucketARN = structure(logical(0), 
        shape = "BucketARN", type = "string", max = 2048L, min = 1L, 
        pattern = "arn:.*"), Prefix = structure(logical(0), shape = "Prefix", 
        type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
        shape = "SizeInMBs", type = "integer", max = 128L, min = 1L), 
        IntervalInSeconds = structure(logical(0), shape = "IntervalInSeconds", 
            type = "integer", max = 900L, min = 60L)), shape = "BufferingHints", 
        type = "structure"), CompressionFormat = structure(logical(0), 
        shape = "CompressionFormat", type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
        shape = "NoEncryptionConfig", type = "string"), KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
        shape = "AWSKMSKeyARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
        type = "structure")), shape = "EncryptionConfiguration", 
        type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
        shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
        shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
        type = "structure")), shape = "S3DestinationDescription", 
        type = "structure"), ProcessingConfiguration = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), Processors = structure(list(structure(list(Type = structure(logical(0), 
        shape = "ProcessorType", type = "string"), Parameters = structure(list(structure(list(ParameterName = structure(logical(0), 
        shape = "ProcessorParameterName", type = "string"), ParameterValue = structure(logical(0), 
        shape = "ProcessorParameterValue", type = "string", max = 512L, 
        min = 1L)), shape = "ProcessorParameter", type = "structure")), 
        shape = "ProcessorParameterList", type = "list")), shape = "Processor", 
        type = "structure")), shape = "ProcessorList", type = "list")), 
        shape = "ProcessingConfiguration", type = "structure"), 
        CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
            shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
            shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
            type = "structure")), shape = "SplunkDestinationDescription", 
        type = "structure")), shape = "DestinationDescription", 
        type = "structure")), shape = "DestinationDescriptionList", 
        type = "list"), HasMoreDestinations = structure(logical(0), 
        shape = "BooleanObject", type = "boolean")), shape = "DeliveryStreamDescription", 
        type = "structure")), shape = "DescribeDeliveryStreamOutput", 
        type = "structure")
    return(populate(args, shape))
}

list_delivery_streams_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Limit = structure(logical(0), shape = "ListDeliveryStreamsInputLimit", 
        type = "integer", max = 10000L, min = 1L), DeliveryStreamType = structure(logical(0), 
        shape = "DeliveryStreamType", type = "string"), ExclusiveStartDeliveryStreamName = structure(logical(0), 
        shape = "DeliveryStreamName", type = "string", max = 64L, 
        min = 1L, pattern = "[a-zA-Z0-9_.-]+")), shape = "ListDeliveryStreamsInput", 
        type = "structure")
    return(populate(args, shape))
}

list_delivery_streams_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(DeliveryStreamNames = structure(list(structure(logical(0), 
        shape = "DeliveryStreamName", type = "string", max = 64L, 
        min = 1L, pattern = "[a-zA-Z0-9_.-]+")), shape = "DeliveryStreamNameList", 
        type = "list"), HasMoreDeliveryStreams = structure(logical(0), 
        shape = "BooleanObject", type = "boolean")), shape = "ListDeliveryStreamsOutput", 
        type = "structure")
    return(populate(args, shape))
}

list_tags_for_delivery_stream_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(DeliveryStreamName = structure(logical(0), 
        shape = "DeliveryStreamName", type = "string", max = 64L, 
        min = 1L, pattern = "[a-zA-Z0-9_.-]+"), ExclusiveStartTagKey = structure(logical(0), 
        shape = "TagKey", type = "string", max = 128L, min = 1L), 
        Limit = structure(logical(0), shape = "ListTagsForDeliveryStreamInputLimit", 
            type = "integer", max = 50L, min = 1L)), shape = "ListTagsForDeliveryStreamInput", 
        type = "structure")
    return(populate(args, shape))
}

list_tags_for_delivery_stream_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(Tags = structure(list(structure(list(Key = structure(logical(0), 
        shape = "TagKey", type = "string", max = 128L, min = 1L), 
        Value = structure(logical(0), shape = "TagValue", type = "string", 
            max = 256L, min = 0L)), shape = "Tag", type = "structure")), 
        shape = "ListTagsForDeliveryStreamOutputTagList", type = "list", 
        max = 50L, min = 0L), HasMoreTags = structure(logical(0), 
        shape = "BooleanObject", type = "boolean")), shape = "ListTagsForDeliveryStreamOutput", 
        type = "structure")
    return(populate(args, shape))
}

put_record_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(DeliveryStreamName = structure(logical(0), 
        shape = "DeliveryStreamName", type = "string", max = 64L, 
        min = 1L, pattern = "[a-zA-Z0-9_.-]+"), Record = structure(list(Data = structure(logical(0), 
        shape = "Data", type = "blob", max = 1024000L, min = 0L)), 
        shape = "Record", type = "structure")), shape = "PutRecordInput", 
        type = "structure")
    return(populate(args, shape))
}

put_record_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(RecordId = structure(logical(0), 
        shape = "PutResponseRecordId", type = "string", min = 1L)), 
        shape = "PutRecordOutput", type = "structure")
    return(populate(args, shape))
}

put_record_batch_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(DeliveryStreamName = structure(logical(0), 
        shape = "DeliveryStreamName", type = "string", max = 64L, 
        min = 1L, pattern = "[a-zA-Z0-9_.-]+"), Records = structure(list(structure(list(Data = structure(logical(0), 
        shape = "Data", type = "blob", max = 1024000L, min = 0L)), 
        shape = "Record", type = "structure")), shape = "PutRecordBatchRequestEntryList", 
        type = "list", max = 500L, min = 1L)), shape = "PutRecordBatchInput", 
        type = "structure")
    return(populate(args, shape))
}

put_record_batch_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(FailedPutCount = structure(logical(0), 
        shape = "NonNegativeIntegerObject", type = "integer", 
        min = 0L), RequestResponses = structure(list(structure(list(RecordId = structure(logical(0), 
        shape = "PutResponseRecordId", type = "string", min = 1L), 
        ErrorCode = structure(logical(0), shape = "ErrorCode", 
            type = "string"), ErrorMessage = structure(logical(0), 
            shape = "ErrorMessage", type = "string")), shape = "PutRecordBatchResponseEntry", 
        type = "structure")), shape = "PutRecordBatchResponseEntryList", 
        type = "list", max = 500L, min = 1L)), shape = "PutRecordBatchOutput", 
        type = "structure")
    return(populate(args, shape))
}

tag_delivery_stream_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(DeliveryStreamName = structure(logical(0), 
        shape = "DeliveryStreamName", type = "string", max = 64L, 
        min = 1L, pattern = "[a-zA-Z0-9_.-]+"), Tags = structure(list(structure(list(Key = structure(logical(0), 
        shape = "TagKey", type = "string", max = 128L, min = 1L), 
        Value = structure(logical(0), shape = "TagValue", type = "string", 
            max = 256L, min = 0L)), shape = "Tag", type = "structure")), 
        shape = "TagDeliveryStreamInputTagList", type = "list", 
        max = 50L, min = 1L)), shape = "TagDeliveryStreamInput", 
        type = "structure")
    return(populate(args, shape))
}

tag_delivery_stream_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(), shape = "TagDeliveryStreamOutput", 
        type = "structure")
    return(populate(args, shape))
}

untag_delivery_stream_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(DeliveryStreamName = structure(logical(0), 
        shape = "DeliveryStreamName", type = "string", max = 64L, 
        min = 1L, pattern = "[a-zA-Z0-9_.-]+"), TagKeys = structure(list(structure(logical(0), 
        shape = "TagKey", type = "string", max = 128L, min = 1L)), 
        shape = "TagKeyList", type = "list", max = 50L, min = 1L)), 
        shape = "UntagDeliveryStreamInput", type = "structure")
    return(populate(args, shape))
}

untag_delivery_stream_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(), shape = "UntagDeliveryStreamOutput", 
        type = "structure")
    return(populate(args, shape))
}

update_destination_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(DeliveryStreamName = structure(logical(0), 
        shape = "DeliveryStreamName", type = "string", max = 64L, 
        min = 1L, pattern = "[a-zA-Z0-9_.-]+"), CurrentDeliveryStreamVersionId = structure(logical(0), 
        shape = "DeliveryStreamVersionId", type = "string", max = 50L, 
        min = 1L, pattern = "[0-9]+"), DestinationId = structure(logical(0), 
        shape = "DestinationId", type = "string", max = 100L, 
        min = 1L), S3DestinationUpdate = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), BucketARN = structure(logical(0), 
        shape = "BucketARN", type = "string", max = 2048L, min = 1L, 
        pattern = "arn:.*"), Prefix = structure(logical(0), shape = "Prefix", 
        type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
        shape = "SizeInMBs", type = "integer", max = 128L, min = 1L), 
        IntervalInSeconds = structure(logical(0), shape = "IntervalInSeconds", 
            type = "integer", max = 900L, min = 60L)), shape = "BufferingHints", 
        type = "structure"), CompressionFormat = structure(logical(0), 
        shape = "CompressionFormat", type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
        shape = "NoEncryptionConfig", type = "string"), KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
        shape = "AWSKMSKeyARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
        type = "structure")), shape = "EncryptionConfiguration", 
        type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
        shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
        shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
        type = "structure")), shape = "S3DestinationUpdate", 
        deprecated = TRUE, type = "structure"), ExtendedS3DestinationUpdate = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), BucketARN = structure(logical(0), 
        shape = "BucketARN", type = "string", max = 2048L, min = 1L, 
        pattern = "arn:.*"), Prefix = structure(logical(0), shape = "Prefix", 
        type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
        shape = "SizeInMBs", type = "integer", max = 128L, min = 1L), 
        IntervalInSeconds = structure(logical(0), shape = "IntervalInSeconds", 
            type = "integer", max = 900L, min = 60L)), shape = "BufferingHints", 
        type = "structure"), CompressionFormat = structure(logical(0), 
        shape = "CompressionFormat", type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
        shape = "NoEncryptionConfig", type = "string"), KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
        shape = "AWSKMSKeyARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
        type = "structure")), shape = "EncryptionConfiguration", 
        type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
        shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
        shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
        type = "structure"), ProcessingConfiguration = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), Processors = structure(list(structure(list(Type = structure(logical(0), 
        shape = "ProcessorType", type = "string"), Parameters = structure(list(structure(list(ParameterName = structure(logical(0), 
        shape = "ProcessorParameterName", type = "string"), ParameterValue = structure(logical(0), 
        shape = "ProcessorParameterValue", type = "string", max = 512L, 
        min = 1L)), shape = "ProcessorParameter", type = "structure")), 
        shape = "ProcessorParameterList", type = "list")), shape = "Processor", 
        type = "structure")), shape = "ProcessorList", type = "list")), 
        shape = "ProcessingConfiguration", type = "structure"), 
        S3BackupMode = structure(logical(0), shape = "S3BackupMode", 
            type = "string"), S3BackupUpdate = structure(list(RoleARN = structure(logical(0), 
            shape = "RoleARN", type = "string", max = 512L, min = 1L, 
            pattern = "arn:.*"), BucketARN = structure(logical(0), 
            shape = "BucketARN", type = "string", max = 2048L, 
            min = 1L, pattern = "arn:.*"), Prefix = structure(logical(0), 
            shape = "Prefix", type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
            shape = "SizeInMBs", type = "integer", max = 128L, 
            min = 1L), IntervalInSeconds = structure(logical(0), 
            shape = "IntervalInSeconds", type = "integer", max = 900L, 
            min = 60L)), shape = "BufferingHints", type = "structure"), 
            CompressionFormat = structure(logical(0), shape = "CompressionFormat", 
                type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
                shape = "NoEncryptionConfig", type = "string"), 
                KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
                  shape = "AWSKMSKeyARN", type = "string", max = 512L, 
                  min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
                  type = "structure")), shape = "EncryptionConfiguration", 
                type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
                shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
                shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
                type = "structure")), shape = "S3DestinationUpdate", 
            type = "structure"), DataFormatConversionConfiguration = structure(list(SchemaConfiguration = structure(list(RoleARN = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), CatalogId = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), DatabaseName = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), TableName = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), Region = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$"), VersionId = structure(logical(0), 
            shape = "NonEmptyStringWithoutWhitespace", type = "string", 
            pattern = "^\\S+$")), shape = "SchemaConfiguration", 
            type = "structure"), InputFormatConfiguration = structure(list(Deserializer = structure(list(OpenXJsonSerDe = structure(list(ConvertDotsInJsonKeysToUnderscores = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), CaseInsensitive = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), ColumnToJsonKeyMappings = structure(list(structure(logical(0), 
            shape = "NonEmptyString", type = "string", pattern = "^(?!\\s*$).+")), 
            shape = "ColumnToJsonKeyMappings", type = "map")), 
            shape = "OpenXJsonSerDe", type = "structure"), HiveJsonSerDe = structure(list(TimestampFormats = structure(list(structure(logical(0), 
            shape = "NonEmptyString", type = "string", pattern = "^(?!\\s*$).+")), 
            shape = "ListOfNonEmptyStrings", type = "list")), 
            shape = "HiveJsonSerDe", type = "structure")), shape = "Deserializer", 
            type = "structure")), shape = "InputFormatConfiguration", 
            type = "structure"), OutputFormatConfiguration = structure(list(Serializer = structure(list(ParquetSerDe = structure(list(BlockSizeBytes = structure(logical(0), 
            shape = "BlockSizeBytes", type = "integer", min = 67108864L), 
            PageSizeBytes = structure(logical(0), shape = "ParquetPageSizeBytes", 
                type = "integer", min = 65536L), Compression = structure(logical(0), 
                shape = "ParquetCompression", type = "string"), 
            EnableDictionaryCompression = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), MaxPaddingBytes = structure(logical(0), 
                shape = "NonNegativeIntegerObject", type = "integer", 
                min = 0L), WriterVersion = structure(logical(0), 
                shape = "ParquetWriterVersion", type = "string")), 
            shape = "ParquetSerDe", type = "structure"), OrcSerDe = structure(list(StripeSizeBytes = structure(logical(0), 
            shape = "OrcStripeSizeBytes", type = "integer", min = 8388608L), 
            BlockSizeBytes = structure(logical(0), shape = "BlockSizeBytes", 
                type = "integer", min = 67108864L), RowIndexStride = structure(logical(0), 
                shape = "OrcRowIndexStride", type = "integer", 
                min = 1000L), EnablePadding = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), PaddingTolerance = structure(logical(0), 
                shape = "Proportion", type = "double", max = 1L, 
                min = 0L), Compression = structure(logical(0), 
                shape = "OrcCompression", type = "string"), BloomFilterColumns = structure(list(structure(logical(0), 
                shape = "NonEmptyStringWithoutWhitespace", type = "string", 
                pattern = "^\\S+$")), shape = "ListOfNonEmptyStringsWithoutWhitespace", 
                type = "list"), BloomFilterFalsePositiveProbability = structure(logical(0), 
                shape = "Proportion", type = "double", max = 1L, 
                min = 0L), DictionaryKeyThreshold = structure(logical(0), 
                shape = "Proportion", type = "double", max = 1L, 
                min = 0L), FormatVersion = structure(logical(0), 
                shape = "OrcFormatVersion", type = "string")), 
            shape = "OrcSerDe", type = "structure")), shape = "Serializer", 
            type = "structure")), shape = "OutputFormatConfiguration", 
            type = "structure"), Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean")), shape = "DataFormatConversionConfiguration", 
            type = "structure")), shape = "ExtendedS3DestinationUpdate", 
        type = "structure"), RedshiftDestinationUpdate = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), ClusterJDBCURL = structure(logical(0), 
        shape = "ClusterJDBCURL", type = "string", min = 1L, 
        pattern = "jdbc:(redshift|postgresql)://((?!-)[A-Za-z0-9-]{1,63}(?<!-)\\.)+redshift\\.amazonaws\\.com:\\d{1,5}/[a-zA-Z0-9_$]+"), 
        CopyCommand = structure(list(DataTableName = structure(logical(0), 
            shape = "DataTableName", type = "string", min = 1L), 
            DataTableColumns = structure(logical(0), shape = "DataTableColumns", 
                type = "string"), CopyOptions = structure(logical(0), 
                shape = "CopyOptions", type = "string")), shape = "CopyCommand", 
            type = "structure"), Username = structure(logical(0), 
            shape = "Username", type = "string", min = 1L, sensitive = TRUE), 
        Password = structure(logical(0), shape = "Password", 
            type = "string", min = 6L, sensitive = TRUE), RetryOptions = structure(list(DurationInSeconds = structure(logical(0), 
            shape = "RedshiftRetryDurationInSeconds", type = "integer", 
            max = 7200L, min = 0L)), shape = "RedshiftRetryOptions", 
            type = "structure"), S3Update = structure(list(RoleARN = structure(logical(0), 
            shape = "RoleARN", type = "string", max = 512L, min = 1L, 
            pattern = "arn:.*"), BucketARN = structure(logical(0), 
            shape = "BucketARN", type = "string", max = 2048L, 
            min = 1L, pattern = "arn:.*"), Prefix = structure(logical(0), 
            shape = "Prefix", type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
            shape = "SizeInMBs", type = "integer", max = 128L, 
            min = 1L), IntervalInSeconds = structure(logical(0), 
            shape = "IntervalInSeconds", type = "integer", max = 900L, 
            min = 60L)), shape = "BufferingHints", type = "structure"), 
            CompressionFormat = structure(logical(0), shape = "CompressionFormat", 
                type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
                shape = "NoEncryptionConfig", type = "string"), 
                KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
                  shape = "AWSKMSKeyARN", type = "string", max = 512L, 
                  min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
                  type = "structure")), shape = "EncryptionConfiguration", 
                type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
                shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
                shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
                type = "structure")), shape = "S3DestinationUpdate", 
            type = "structure"), ProcessingConfiguration = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), Processors = structure(list(structure(list(Type = structure(logical(0), 
            shape = "ProcessorType", type = "string"), Parameters = structure(list(structure(list(ParameterName = structure(logical(0), 
            shape = "ProcessorParameterName", type = "string"), 
            ParameterValue = structure(logical(0), shape = "ProcessorParameterValue", 
                type = "string", max = 512L, min = 1L)), shape = "ProcessorParameter", 
            type = "structure")), shape = "ProcessorParameterList", 
            type = "list")), shape = "Processor", type = "structure")), 
            shape = "ProcessorList", type = "list")), shape = "ProcessingConfiguration", 
            type = "structure"), S3BackupMode = structure(logical(0), 
            shape = "RedshiftS3BackupMode", type = "string"), 
        S3BackupUpdate = structure(list(RoleARN = structure(logical(0), 
            shape = "RoleARN", type = "string", max = 512L, min = 1L, 
            pattern = "arn:.*"), BucketARN = structure(logical(0), 
            shape = "BucketARN", type = "string", max = 2048L, 
            min = 1L, pattern = "arn:.*"), Prefix = structure(logical(0), 
            shape = "Prefix", type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
            shape = "SizeInMBs", type = "integer", max = 128L, 
            min = 1L), IntervalInSeconds = structure(logical(0), 
            shape = "IntervalInSeconds", type = "integer", max = 900L, 
            min = 60L)), shape = "BufferingHints", type = "structure"), 
            CompressionFormat = structure(logical(0), shape = "CompressionFormat", 
                type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
                shape = "NoEncryptionConfig", type = "string"), 
                KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
                  shape = "AWSKMSKeyARN", type = "string", max = 512L, 
                  min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
                  type = "structure")), shape = "EncryptionConfiguration", 
                type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
                shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
                shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
                type = "structure")), shape = "S3DestinationUpdate", 
            type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
            shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
            shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
            type = "structure")), shape = "RedshiftDestinationUpdate", 
        type = "structure"), ElasticsearchDestinationUpdate = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), DomainARN = structure(logical(0), 
        shape = "ElasticsearchDomainARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*"), IndexName = structure(logical(0), 
        shape = "ElasticsearchIndexName", type = "string", max = 80L, 
        min = 1L), TypeName = structure(logical(0), shape = "ElasticsearchTypeName", 
        type = "string", max = 100L, min = 1L), IndexRotationPeriod = structure(logical(0), 
        shape = "ElasticsearchIndexRotationPeriod", type = "string"), 
        BufferingHints = structure(list(IntervalInSeconds = structure(logical(0), 
            shape = "ElasticsearchBufferingIntervalInSeconds", 
            type = "integer", max = 900L, min = 60L), SizeInMBs = structure(logical(0), 
            shape = "ElasticsearchBufferingSizeInMBs", type = "integer", 
            max = 100L, min = 1L)), shape = "ElasticsearchBufferingHints", 
            type = "structure"), RetryOptions = structure(list(DurationInSeconds = structure(logical(0), 
            shape = "ElasticsearchRetryDurationInSeconds", type = "integer", 
            max = 7200L, min = 0L)), shape = "ElasticsearchRetryOptions", 
            type = "structure"), S3Update = structure(list(RoleARN = structure(logical(0), 
            shape = "RoleARN", type = "string", max = 512L, min = 1L, 
            pattern = "arn:.*"), BucketARN = structure(logical(0), 
            shape = "BucketARN", type = "string", max = 2048L, 
            min = 1L, pattern = "arn:.*"), Prefix = structure(logical(0), 
            shape = "Prefix", type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
            shape = "SizeInMBs", type = "integer", max = 128L, 
            min = 1L), IntervalInSeconds = structure(logical(0), 
            shape = "IntervalInSeconds", type = "integer", max = 900L, 
            min = 60L)), shape = "BufferingHints", type = "structure"), 
            CompressionFormat = structure(logical(0), shape = "CompressionFormat", 
                type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
                shape = "NoEncryptionConfig", type = "string"), 
                KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
                  shape = "AWSKMSKeyARN", type = "string", max = 512L, 
                  min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
                  type = "structure")), shape = "EncryptionConfiguration", 
                type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
                shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
                shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
                shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
                type = "structure")), shape = "S3DestinationUpdate", 
            type = "structure"), ProcessingConfiguration = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), Processors = structure(list(structure(list(Type = structure(logical(0), 
            shape = "ProcessorType", type = "string"), Parameters = structure(list(structure(list(ParameterName = structure(logical(0), 
            shape = "ProcessorParameterName", type = "string"), 
            ParameterValue = structure(logical(0), shape = "ProcessorParameterValue", 
                type = "string", max = 512L, min = 1L)), shape = "ProcessorParameter", 
            type = "structure")), shape = "ProcessorParameterList", 
            type = "list")), shape = "Processor", type = "structure")), 
            shape = "ProcessorList", type = "list")), shape = "ProcessingConfiguration", 
            type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
            shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
            shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
            type = "structure")), shape = "ElasticsearchDestinationUpdate", 
        type = "structure"), SplunkDestinationUpdate = structure(list(HECEndpoint = structure(logical(0), 
        shape = "HECEndpoint", type = "string"), HECEndpointType = structure(logical(0), 
        shape = "HECEndpointType", type = "string"), HECToken = structure(logical(0), 
        shape = "HECToken", type = "string"), HECAcknowledgmentTimeoutInSeconds = structure(logical(0), 
        shape = "HECAcknowledgmentTimeoutInSeconds", type = "integer", 
        max = 600L, min = 180L), RetryOptions = structure(list(DurationInSeconds = structure(logical(0), 
        shape = "SplunkRetryDurationInSeconds", type = "integer", 
        max = 7200L, min = 0L)), shape = "SplunkRetryOptions", 
        type = "structure"), S3BackupMode = structure(logical(0), 
        shape = "SplunkS3BackupMode", type = "string"), S3Update = structure(list(RoleARN = structure(logical(0), 
        shape = "RoleARN", type = "string", max = 512L, min = 1L, 
        pattern = "arn:.*"), BucketARN = structure(logical(0), 
        shape = "BucketARN", type = "string", max = 2048L, min = 1L, 
        pattern = "arn:.*"), Prefix = structure(logical(0), shape = "Prefix", 
        type = "string"), BufferingHints = structure(list(SizeInMBs = structure(logical(0), 
        shape = "SizeInMBs", type = "integer", max = 128L, min = 1L), 
        IntervalInSeconds = structure(logical(0), shape = "IntervalInSeconds", 
            type = "integer", max = 900L, min = 60L)), shape = "BufferingHints", 
        type = "structure"), CompressionFormat = structure(logical(0), 
        shape = "CompressionFormat", type = "string"), EncryptionConfiguration = structure(list(NoEncryptionConfig = structure(logical(0), 
        shape = "NoEncryptionConfig", type = "string"), KMSEncryptionConfig = structure(list(AWSKMSKeyARN = structure(logical(0), 
        shape = "AWSKMSKeyARN", type = "string", max = 512L, 
        min = 1L, pattern = "arn:.*")), shape = "KMSEncryptionConfig", 
        type = "structure")), shape = "EncryptionConfiguration", 
        type = "structure"), CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
        shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
        shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
        type = "structure")), shape = "S3DestinationUpdate", 
        type = "structure"), ProcessingConfiguration = structure(list(Enabled = structure(logical(0), 
        shape = "BooleanObject", type = "boolean"), Processors = structure(list(structure(list(Type = structure(logical(0), 
        shape = "ProcessorType", type = "string"), Parameters = structure(list(structure(list(ParameterName = structure(logical(0), 
        shape = "ProcessorParameterName", type = "string"), ParameterValue = structure(logical(0), 
        shape = "ProcessorParameterValue", type = "string", max = 512L, 
        min = 1L)), shape = "ProcessorParameter", type = "structure")), 
        shape = "ProcessorParameterList", type = "list")), shape = "Processor", 
        type = "structure")), shape = "ProcessorList", type = "list")), 
        shape = "ProcessingConfiguration", type = "structure"), 
        CloudWatchLoggingOptions = structure(list(Enabled = structure(logical(0), 
            shape = "BooleanObject", type = "boolean"), LogGroupName = structure(logical(0), 
            shape = "LogGroupName", type = "string"), LogStreamName = structure(logical(0), 
            shape = "LogStreamName", type = "string")), shape = "CloudWatchLoggingOptions", 
            type = "structure")), shape = "SplunkDestinationUpdate", 
        type = "structure")), shape = "UpdateDestinationInput", 
        type = "structure")
    return(populate(args, shape))
}

update_destination_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(), shape = "UpdateDestinationOutput", 
        type = "structure")
    return(populate(args, shape))
}
