# This file is generated by make.paws. Please do not edit here.

batch_check_layer_availability_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        layerDigests = structure(list(structure(logical(0), tags = list(type = "string", 
            max = 1000L, min = 0L))), tags = list(type = "list", 
            max = 100L, min = 1L))), tags = list(type = "structure"))
    return(populate(args, shape))
}

batch_check_layer_availability_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(layers = structure(list(structure(list(layerDigest = structure(logical(0), 
        tags = list(type = "string", pattern = "[a-zA-Z0-9-_+.]+:[a-fA-F0-9]+")), 
        layerAvailability = structure(logical(0), tags = list(type = "string", 
            enum = c("AVAILABLE", "UNAVAILABLE"))), layerSize = structure(logical(0), 
            tags = list(type = "long")), mediaType = structure(logical(0), 
            tags = list(type = "string"))), tags = list(type = "structure"))), 
        tags = list(type = "list")), failures = structure(list(structure(list(layerDigest = structure(logical(0), 
        tags = list(type = "string", max = 1000L, min = 0L)), 
        failureCode = structure(logical(0), tags = list(type = "string", 
            enum = c("InvalidLayerDigest", "MissingLayerDigest"))), 
        failureReason = structure(logical(0), tags = list(type = "string"))), 
        tags = list(type = "structure"))), tags = list(type = "list"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

batch_delete_image_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        imageIds = structure(list(structure(list(imageDigest = structure(logical(0), 
            tags = list(type = "string")), imageTag = structure(logical(0), 
            tags = list(type = "string"))), tags = list(type = "structure"))), 
            tags = list(type = "list", max = 100L, min = 1L))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

batch_delete_image_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(imageIds = structure(list(structure(list(imageDigest = structure(logical(0), 
        tags = list(type = "string")), imageTag = structure(logical(0), 
        tags = list(type = "string"))), tags = list(type = "structure"))), 
        tags = list(type = "list", max = 100L, min = 1L)), failures = structure(list(structure(list(imageId = structure(list(imageDigest = structure(logical(0), 
        tags = list(type = "string")), imageTag = structure(logical(0), 
        tags = list(type = "string"))), tags = list(type = "structure")), 
        failureCode = structure(logical(0), tags = list(type = "string", 
            enum = c("InvalidImageDigest", "InvalidImageTag", 
                "ImageTagDoesNotMatchDigest", "ImageNotFound", 
                "MissingDigestAndTag"))), failureReason = structure(logical(0), 
            tags = list(type = "string"))), tags = list(type = "structure"))), 
        tags = list(type = "list"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

batch_get_image_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        imageIds = structure(list(structure(list(imageDigest = structure(logical(0), 
            tags = list(type = "string")), imageTag = structure(logical(0), 
            tags = list(type = "string"))), tags = list(type = "structure"))), 
            tags = list(type = "list", max = 100L, min = 1L)), 
        acceptedMediaTypes = structure(list(structure(logical(0), 
            tags = list(type = "string"))), tags = list(type = "list", 
            max = 100L, min = 1L))), tags = list(type = "structure"))
    return(populate(args, shape))
}

batch_get_image_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(images = structure(list(structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        imageId = structure(list(imageDigest = structure(logical(0), 
            tags = list(type = "string")), imageTag = structure(logical(0), 
            tags = list(type = "string"))), tags = list(type = "structure")), 
        imageManifest = structure(logical(0), tags = list(type = "string"))), 
        tags = list(type = "structure"))), tags = list(type = "list")), 
        failures = structure(list(structure(list(imageId = structure(list(imageDigest = structure(logical(0), 
            tags = list(type = "string")), imageTag = structure(logical(0), 
            tags = list(type = "string"))), tags = list(type = "structure")), 
            failureCode = structure(logical(0), tags = list(type = "string", 
                enum = c("InvalidImageDigest", "InvalidImageTag", 
                  "ImageTagDoesNotMatchDigest", "ImageNotFound", 
                  "MissingDigestAndTag"))), failureReason = structure(logical(0), 
                tags = list(type = "string"))), tags = list(type = "structure"))), 
            tags = list(type = "list"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

complete_layer_upload_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        uploadId = structure(logical(0), tags = list(type = "string", 
            pattern = "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")), 
        layerDigests = structure(list(structure(logical(0), tags = list(type = "string", 
            pattern = "[a-zA-Z0-9-_+.]+:[a-fA-F0-9]+"))), tags = list(type = "list", 
            max = 100L, min = 1L))), tags = list(type = "structure"))
    return(populate(args, shape))
}

complete_layer_upload_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        uploadId = structure(logical(0), tags = list(type = "string", 
            pattern = "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")), 
        layerDigest = structure(logical(0), tags = list(type = "string", 
            pattern = "[a-zA-Z0-9-_+.]+:[a-fA-F0-9]+"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

create_repository_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(repositoryName = structure(logical(0), 
        tags = list(type = "string", max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        tags = structure(list(structure(list(Key = structure(logical(0), 
            tags = list(type = "string")), Value = structure(logical(0), 
            tags = list(type = "string"))), tags = list(type = "structure"))), 
            tags = list(type = "list"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

create_repository_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(repository = structure(list(repositoryArn = structure(logical(0), 
        tags = list(type = "string")), registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        repositoryUri = structure(logical(0), tags = list(type = "string")), 
        createdAt = structure(logical(0), tags = list(type = "timestamp"))), 
        tags = list(type = "structure"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

delete_lifecycle_policy_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

delete_lifecycle_policy_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        lifecyclePolicyText = structure(logical(0), tags = list(type = "string", 
            max = 30720L, min = 100L)), lastEvaluatedAt = structure(logical(0), 
            tags = list(type = "timestamp"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

delete_repository_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        force = structure(logical(0), tags = list(type = "boolean"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

delete_repository_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(repository = structure(list(repositoryArn = structure(logical(0), 
        tags = list(type = "string")), registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        repositoryUri = structure(logical(0), tags = list(type = "string")), 
        createdAt = structure(logical(0), tags = list(type = "timestamp"))), 
        tags = list(type = "structure"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

delete_repository_policy_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

delete_repository_policy_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        policyText = structure(logical(0), tags = list(type = "string", 
            max = 10240L, min = 0L))), tags = list(type = "structure"))
    return(populate(args, shape))
}

describe_images_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        imageIds = structure(list(structure(list(imageDigest = structure(logical(0), 
            tags = list(type = "string")), imageTag = structure(logical(0), 
            tags = list(type = "string"))), tags = list(type = "structure"))), 
            tags = list(type = "list", max = 100L, min = 1L)), 
        nextToken = structure(logical(0), tags = list(type = "string")), 
        maxResults = structure(logical(0), tags = list(type = "integer", 
            max = 1000L, min = 1L)), filter = structure(list(tagStatus = structure(logical(0), 
            tags = list(type = "string", enum = c("TAGGED", "UNTAGGED", 
                "ANY")))), tags = list(type = "structure"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

describe_images_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(imageDetails = structure(list(structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        imageDigest = structure(logical(0), tags = list(type = "string")), 
        imageTags = structure(list(structure(logical(0), tags = list(type = "string"))), 
            tags = list(type = "list")), imageSizeInBytes = structure(logical(0), 
            tags = list(type = "long")), imagePushedAt = structure(logical(0), 
            tags = list(type = "timestamp"))), tags = list(type = "structure"))), 
        tags = list(type = "list")), nextToken = structure(logical(0), 
        tags = list(type = "string"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

describe_repositories_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryNames = structure(list(structure(logical(0), 
            tags = list(type = "string", max = 256L, min = 2L, 
                pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*"))), 
            tags = list(type = "list", max = 100L, min = 1L)), 
        nextToken = structure(logical(0), tags = list(type = "string")), 
        maxResults = structure(logical(0), tags = list(type = "integer", 
            max = 1000L, min = 1L))), tags = list(type = "structure"))
    return(populate(args, shape))
}

describe_repositories_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(repositories = structure(list(structure(list(repositoryArn = structure(logical(0), 
        tags = list(type = "string")), registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        repositoryUri = structure(logical(0), tags = list(type = "string")), 
        createdAt = structure(logical(0), tags = list(type = "timestamp"))), 
        tags = list(type = "structure"))), tags = list(type = "list")), 
        nextToken = structure(logical(0), tags = list(type = "string"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

get_authorization_token_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryIds = structure(list(structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}"))), 
        tags = list(type = "list", max = 10L, min = 1L))), tags = list(type = "structure"))
    return(populate(args, shape))
}

get_authorization_token_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(authorizationData = structure(list(structure(list(authorizationToken = structure(logical(0), 
        tags = list(type = "string", pattern = "^\\S+$")), expiresAt = structure(logical(0), 
        tags = list(type = "timestamp")), proxyEndpoint = structure(logical(0), 
        tags = list(type = "string"))), tags = list(type = "structure"))), 
        tags = list(type = "list"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

get_download_url_for_layer_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        layerDigest = structure(logical(0), tags = list(type = "string", 
            pattern = "[a-zA-Z0-9-_+.]+:[a-fA-F0-9]+"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

get_download_url_for_layer_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(downloadUrl = structure(logical(0), 
        tags = list(type = "string")), layerDigest = structure(logical(0), 
        tags = list(type = "string", pattern = "[a-zA-Z0-9-_+.]+:[a-fA-F0-9]+"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

get_lifecycle_policy_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

get_lifecycle_policy_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        lifecyclePolicyText = structure(logical(0), tags = list(type = "string", 
            max = 30720L, min = 100L)), lastEvaluatedAt = structure(logical(0), 
            tags = list(type = "timestamp"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

get_lifecycle_policy_preview_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        imageIds = structure(list(structure(list(imageDigest = structure(logical(0), 
            tags = list(type = "string")), imageTag = structure(logical(0), 
            tags = list(type = "string"))), tags = list(type = "structure"))), 
            tags = list(type = "list", max = 100L, min = 1L)), 
        nextToken = structure(logical(0), tags = list(type = "string")), 
        maxResults = structure(logical(0), tags = list(type = "integer", 
            max = 100L, min = 1L)), filter = structure(list(tagStatus = structure(logical(0), 
            tags = list(type = "string", enum = c("TAGGED", "UNTAGGED", 
                "ANY")))), tags = list(type = "structure"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

get_lifecycle_policy_preview_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        lifecyclePolicyText = structure(logical(0), tags = list(type = "string", 
            max = 30720L, min = 100L)), status = structure(logical(0), 
            tags = list(type = "string", enum = c("IN_PROGRESS", 
                "COMPLETE", "EXPIRED", "FAILED"))), nextToken = structure(logical(0), 
            tags = list(type = "string")), previewResults = structure(list(structure(list(imageTags = structure(list(structure(logical(0), 
            tags = list(type = "string"))), tags = list(type = "list")), 
            imageDigest = structure(logical(0), tags = list(type = "string")), 
            imagePushedAt = structure(logical(0), tags = list(type = "timestamp")), 
            action = structure(list(type = structure(logical(0), 
                tags = list(type = "string", enum = "EXPIRE"))), 
                tags = list(type = "structure")), appliedRulePriority = structure(logical(0), 
                tags = list(type = "integer", min = 1L))), tags = list(type = "structure"))), 
            tags = list(type = "list")), summary = structure(list(expiringImageTotalCount = structure(logical(0), 
            tags = list(type = "integer", min = 0L))), tags = list(type = "structure"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

get_repository_policy_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

get_repository_policy_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        policyText = structure(logical(0), tags = list(type = "string", 
            max = 10240L, min = 0L))), tags = list(type = "structure"))
    return(populate(args, shape))
}

initiate_layer_upload_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

initiate_layer_upload_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(uploadId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")), 
        partSize = structure(logical(0), tags = list(type = "long", 
            min = 0L))), tags = list(type = "structure"))
    return(populate(args, shape))
}

list_images_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        nextToken = structure(logical(0), tags = list(type = "string")), 
        maxResults = structure(logical(0), tags = list(type = "integer", 
            max = 1000L, min = 1L)), filter = structure(list(tagStatus = structure(logical(0), 
            tags = list(type = "string", enum = c("TAGGED", "UNTAGGED", 
                "ANY")))), tags = list(type = "structure"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

list_images_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(imageIds = structure(list(structure(list(imageDigest = structure(logical(0), 
        tags = list(type = "string")), imageTag = structure(logical(0), 
        tags = list(type = "string"))), tags = list(type = "structure"))), 
        tags = list(type = "list", max = 100L, min = 1L)), nextToken = structure(logical(0), 
        tags = list(type = "string"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

list_tags_for_resource_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(resourceArn = structure(logical(0), 
        tags = list(type = "string"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

list_tags_for_resource_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(tags = structure(list(structure(list(Key = structure(logical(0), 
        tags = list(type = "string")), Value = structure(logical(0), 
        tags = list(type = "string"))), tags = list(type = "structure"))), 
        tags = list(type = "list"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

put_image_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        imageManifest = structure(logical(0), tags = list(type = "string")), 
        imageTag = structure(logical(0), tags = list(type = "string"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

put_image_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(image = structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        imageId = structure(list(imageDigest = structure(logical(0), 
            tags = list(type = "string")), imageTag = structure(logical(0), 
            tags = list(type = "string"))), tags = list(type = "structure")), 
        imageManifest = structure(logical(0), tags = list(type = "string"))), 
        tags = list(type = "structure"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

put_lifecycle_policy_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        lifecyclePolicyText = structure(logical(0), tags = list(type = "string", 
            max = 30720L, min = 100L))), tags = list(type = "structure"))
    return(populate(args, shape))
}

put_lifecycle_policy_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        lifecyclePolicyText = structure(logical(0), tags = list(type = "string", 
            max = 30720L, min = 100L))), tags = list(type = "structure"))
    return(populate(args, shape))
}

set_repository_policy_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        policyText = structure(logical(0), tags = list(type = "string", 
            max = 10240L, min = 0L)), force = structure(logical(0), 
            tags = list(type = "boolean"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

set_repository_policy_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        policyText = structure(logical(0), tags = list(type = "string", 
            max = 10240L, min = 0L))), tags = list(type = "structure"))
    return(populate(args, shape))
}

start_lifecycle_policy_preview_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        lifecyclePolicyText = structure(logical(0), tags = list(type = "string", 
            max = 30720L, min = 100L))), tags = list(type = "structure"))
    return(populate(args, shape))
}

start_lifecycle_policy_preview_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        lifecyclePolicyText = structure(logical(0), tags = list(type = "string", 
            max = 30720L, min = 100L)), status = structure(logical(0), 
            tags = list(type = "string", enum = c("IN_PROGRESS", 
                "COMPLETE", "EXPIRED", "FAILED")))), tags = list(type = "structure"))
    return(populate(args, shape))
}

tag_resource_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(resourceArn = structure(logical(0), 
        tags = list(type = "string")), tags = structure(list(structure(list(Key = structure(logical(0), 
        tags = list(type = "string")), Value = structure(logical(0), 
        tags = list(type = "string"))), tags = list(type = "structure"))), 
        tags = list(type = "list"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

tag_resource_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(), tags = list(type = "structure"))
    return(populate(args, shape))
}

untag_resource_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(resourceArn = structure(logical(0), 
        tags = list(type = "string")), tagKeys = structure(list(structure(logical(0), 
        tags = list(type = "string"))), tags = list(type = "list"))), 
        tags = list(type = "structure"))
    return(populate(args, shape))
}

untag_resource_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(), tags = list(type = "structure"))
    return(populate(args, shape))
}

upload_layer_part_input <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        uploadId = structure(logical(0), tags = list(type = "string", 
            pattern = "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")), 
        partFirstByte = structure(logical(0), tags = list(type = "long", 
            min = 0L)), partLastByte = structure(logical(0), 
            tags = list(type = "long", min = 0L)), layerPartBlob = structure(logical(0), 
            tags = list(type = "blob"))), tags = list(type = "structure"))
    return(populate(args, shape))
}

upload_layer_part_output <- function (...) 
{
    args <- c(as.list(environment()), list(...))
    shape <- structure(list(registryId = structure(logical(0), 
        tags = list(type = "string", pattern = "[0-9]{12}")), 
        repositoryName = structure(logical(0), tags = list(type = "string", 
            max = 256L, min = 2L, pattern = "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*")), 
        uploadId = structure(logical(0), tags = list(type = "string", 
            pattern = "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")), 
        lastByteReceived = structure(logical(0), tags = list(type = "long", 
            min = 0L))), tags = list(type = "structure"))
    return(populate(args, shape))
}
