# This file is generated by make.paws. Please do not edit here.

#' @include handlers.R
#' @include handlers_restjson.R
#' @include signer_v4.R
NULL

HANDLERS <- Handlers(
  validate = HandlerList(
    validate_endpoint_handler,
    validate_parameters_handler
  ),
  build = HandlerList(
    sdk_version_user_agent_handler,
    add_host_exec_env_user_agent_handler,
    restjson_build
  ),
  sign = HandlerList(
    build_content_length_handler,
    v4_sign_request_handler
  ),
  send = HandlerList(
    validate_req_sig_handler,
    send_handler
  ),
  validate_response = HandlerList(
    validate_response_handler
  ),
  unmarshal = HandlerList(
    restjson_unmarshal
  ),
  unmarshal_meta = HandlerList(
    restjson_unmarshal_meta
  ),
  unmarshal_error = HandlerList(
    restjson_unmarshal_error
  )
)

service <- function () {
  cfg <- client_config(
    service_name = "data.iot",
    endpoints = list("*" = "data.iot.{region}.amazonaws.com", "cn-*" = "data.iot.{region}.amazonaws.com.cn")
  )
  client_info <- ClientInfo(
    service_name = "data.iot",
    service_id = "IoT Data Plane",
    api_version = "2015-05-28",
    signing_name = "iotdata",
    signing_region = cfg$signing_region,
    endpoint = cfg$endpoint,
    json_version = "",
    target_prefix = ""
  )
  handlers <- HANDLERS
  svc <- Client(
    config = cfg$config,
    client_info = client_info,
    handlers = handlers
  )
  return(svc)
}

