# This file is generated by make.paws. Please do not edit here.
#' @importFrom paws.common populate
#' @include mediastoredata_service.R
NULL

.mediastoredata$delete_object_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(Path = structure(logical(0), tags = list(location = "uri", locationName = "Path", type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.mediastoredata$delete_object_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(), tags = list(type = "structure"))
  return(populate(args, shape))
}

.mediastoredata$describe_object_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(Path = structure(logical(0), tags = list(location = "uri", locationName = "Path", type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.mediastoredata$describe_object_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(ETag = structure(logical(0), tags = list(location = "header", locationName = "ETag", type = "string")), ContentType = structure(logical(0), tags = list(location = "header", locationName = "Content-Type", type = "string")), ContentLength = structure(logical(0), tags = list(location = "header", locationName = "Content-Length", type = "long")), CacheControl = structure(logical(0), tags = list(location = "header", locationName = "Cache-Control", type = "string")), LastModified = structure(logical(0), tags = list(location = "header", locationName = "Last-Modified", type = "timestamp"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.mediastoredata$get_object_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(Path = structure(logical(0), tags = list(location = "uri", locationName = "Path", type = "string")), Range = structure(logical(0), tags = list(location = "header", locationName = "Range", type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.mediastoredata$get_object_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(Body = structure(logical(0), tags = list(type = "blob", streaming = TRUE)), CacheControl = structure(logical(0), tags = list(location = "header", locationName = "Cache-Control", type = "string")), ContentRange = structure(logical(0), tags = list(location = "header", locationName = "Content-Range", type = "string")), ContentLength = structure(logical(0), tags = list(location = "header", locationName = "Content-Length", type = "long")), ContentType = structure(logical(0), tags = list(location = "header", locationName = "Content-Type", type = "string")), ETag = structure(logical(0), tags = list(location = "header", locationName = "ETag", type = "string")), LastModified = structure(logical(0), tags = list(location = "header", locationName = "Last-Modified", type = "timestamp")), StatusCode = structure(logical(0), tags = list(location = "statusCode", type = "integer"))), tags = list(type = "structure", payload = "Body"))
  return(populate(args, shape))
}

.mediastoredata$list_items_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(Path = structure(logical(0), tags = list(location = "querystring", locationName = "Path", type = "string")), MaxResults = structure(logical(0), tags = list(location = "querystring", locationName = "MaxResults", type = "integer")), NextToken = structure(logical(0), tags = list(location = "querystring", locationName = "NextToken", type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.mediastoredata$list_items_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(Items = structure(list(structure(list(Name = structure(logical(0), tags = list(type = "string")), Type = structure(logical(0), tags = list(type = "string")), ETag = structure(logical(0), tags = list(type = "string")), LastModified = structure(logical(0), tags = list(type = "timestamp")), ContentType = structure(logical(0), tags = list(type = "string")), ContentLength = structure(logical(0), tags = list(type = "long"))), tags = list(type = "structure"))), tags = list(type = "list")), NextToken = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.mediastoredata$put_object_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(Body = structure(logical(0), tags = list(type = "blob", streaming = TRUE)), Path = structure(logical(0), tags = list(location = "uri", locationName = "Path", type = "string")), ContentType = structure(logical(0), tags = list(location = "header", locationName = "Content-Type", type = "string")), CacheControl = structure(logical(0), tags = list(location = "header", locationName = "Cache-Control", type = "string")), StorageClass = structure(logical(0), tags = list(location = "header", locationName = "x-amz-storage-class", type = "string")), UploadAvailability = structure(logical(0), tags = list(location = "header", locationName = "x-amz-upload-availability", type = "string"))), tags = list(type = "structure", payload = "Body"))
  return(populate(args, shape))
}

.mediastoredata$put_object_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(ContentSHA256 = structure(logical(0), tags = list(type = "string")), ETag = structure(logical(0), tags = list(type = "string")), StorageClass = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}
