# This file is generated by make.paws. Please do not edit here.
#' @importFrom paws.common new_handlers new_service
NULL

#' AWS Import/Export
#'
#' @description
#' AWS Import/Export Service AWS Import/Export accelerates transferring
#' large amounts of data between the AWS cloud and portable storage devices
#' that you mail to us. AWS Import/Export transfers data directly onto and
#' off of your storage devices using Amazon\'s high-speed internal network
#' and bypassing the Internet. For large data sets, AWS Import/Export is
#' often faster than Internet transfer and more cost effective than
#' upgrading your connectivity.
#'
#' @section Example:
#' ```
#' importexport <- paws::importexport()
#' importexport$operation()
#' ```
#'
#' @section Operations:
#' \tabular{ll}{
#'  \link[=importexport_cancel_job]{cancel_job} \tab This operation cancels a specified job \cr
#'  \link[=importexport_create_job]{create_job} \tab This operation initiates the process of scheduling an upload or download of your data \cr
#'  \link[=importexport_get_shipping_label]{get_shipping_label} \tab This operation generates a pre-paid UPS shipping label that you will use to ship your device to AWS for processing \cr
#'  \link[=importexport_get_status]{get_status} \tab This operation returns information about a job, including where the job is in the processing pipeline, the status of the results, and the signature value associated with the job\cr
#'  \link[=importexport_list_jobs]{list_jobs} \tab This operation returns the jobs associated with the requester \cr
#'  \link[=importexport_update_job]{update_job} \tab You use this operation to change the parameters specified in the original manifest file by supplying a new manifest file 
#' }
#'
#' @rdname importexport
#' @export
importexport <- function() {
  .importexport$operations
}

# Private API objects: metadata, handlers, interfaces, etc.
.importexport <- list()

.importexport$operations <- list()

.importexport$metadata <- list(
  service_name = "importexport",
  endpoints = list("*" = "importexport.amazonaws.com"),
  service_id = "ImportExport",
  api_version = "2010-06-01",
  signing_name = NULL,
  json_version = "",
  target_prefix = ""
)

.importexport$handlers <- new_handlers("query", "v2")

.importexport$service <- function() {
  new_service(.importexport$metadata, .importexport$handlers)
}
