# This file is generated by make.paws. Please do not edit here.
#' @importFrom paws.common populate
#' @include connectcontactlens_service.R
NULL

.connectcontactlens$list_realtime_contact_analysis_segments_input <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(InstanceId = structure(logical(0), tags = list(type = "string")), ContactId = structure(logical(0), tags = list(type = "string")), MaxResults = structure(logical(0), tags = list(type = "integer")), NextToken = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}

.connectcontactlens$list_realtime_contact_analysis_segments_output <- function(...) {
  args <- c(as.list(environment()), list(...))
  shape <- structure(list(Segments = structure(list(structure(list(Transcript = structure(list(Id = structure(logical(0), tags = list(type = "string")), ParticipantId = structure(logical(0), tags = list(type = "string")), ParticipantRole = structure(logical(0), tags = list(type = "string")), Content = structure(logical(0), tags = list(type = "string")), BeginOffsetMillis = structure(logical(0), tags = list(type = "integer")), EndOffsetMillis = structure(logical(0), tags = list(type = "integer")), Sentiment = structure(logical(0), tags = list(type = "string")), IssuesDetected = structure(list(structure(list(CharacterOffsets = structure(list(BeginOffsetChar = structure(logical(0), tags = list(type = "integer")), EndOffsetChar = structure(logical(0), tags = list(type = "integer"))), tags = list(type = "structure"))), tags = list(type = "structure"))), tags = list(type = "list"))), tags = list(type = "structure")), Categories = structure(list(MatchedCategories = structure(list(structure(logical(0), tags = list(type = "string"))), tags = list(type = "list")), MatchedDetails = structure(list(structure(list(PointsOfInterest = structure(list(structure(list(BeginOffsetMillis = structure(logical(0), tags = list(type = "integer")), EndOffsetMillis = structure(logical(0), tags = list(type = "integer"))), tags = list(type = "structure"))), tags = list(type = "list"))), tags = list(type = "structure"))), tags = list(type = "map"))), tags = list(type = "structure")), PostContactSummary = structure(list(Content = structure(logical(0), tags = list(type = "string")), Status = structure(logical(0), tags = list(type = "string")), FailureCode = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))), tags = list(type = "structure"))), tags = list(type = "list")), NextToken = structure(logical(0), tags = list(type = "string"))), tags = list(type = "structure"))
  return(populate(args, shape))
}
