# This file is generated by make.paws. Please do not edit here.

test_that("list_activities", {
    expect_error(list_activities(), NA)
})

test_that("list_state_machines", {
    expect_error(list_state_machines(), NA)
})
